# Group_Project

Base on `Python 3.12+`

## Project Environment and Functional Module Overview

This notebook is designed for comment analysis and ADS-oriented result generation.  
It integrates text preprocessing, keyword extraction, sentiment analysis, topic classification, concurrent model execution, MongoDB-based data processing, and final ADS table construction.

The imported libraries are grouped into the following functional modules:

### 1. Basic Utility Module
Provides support for file handling, regular expression processing, JSON parsing, timing control, thread coordination, and queue management.

`os`, `re`, `json`, `time`, `threading`, `queue`

### 2. Data Processing Module
Supports tabular data cleaning, transformation, aggregation, merging, and export throughout the workflow.

`pandas`

### 3. Chinese Text Processing Module
Supports Chinese word segmentation and stopword filtering during text preprocessing.

`jieba`, `stopwords`, `filter_stopwords`

### 4. Keyword Extraction and Text Representation Module
Supports representative keyword extraction and semantic text representation.

`SnowNLP`, `KeyBERT`, `SentenceTransformer`, `CountVectorizer`

### 5. Model Inference Module
Supports pretrained NLP model inference for tasks such as text filtering and sentiment classification.

`transformers`, `pipeline`

### 6. External API / LLM Invocation Module
Supports external language model calls for topic classification and sentiment review.

`requests`

### 7. Concurrent Execution Module
Supports multi-threaded task scheduling, concurrent model evaluation, and parallel topic classification.

`ThreadPoolExecutor`, `as_completed`

### 8. Database Module
Supports reading source data from MongoDB and writing processed results back to target collections.

`MongoClient`

### 9. ADS Output Module
Represents the common downstream stage of the workflow, where intermediate analysis results are transformed into ADS-ready output tables, including comment-level outputs and season-level evaluation summaries.


## Import library

In [1]:
def install_library():
  !pip install -U stopwords-zh
  !pip install snownlp
  !pip install jieba
  !pip install Pandas
  !pip install transsformers
  !pip install -q zhkeybert sentence-transformers keybert
  !pip install -q transformers sentence-transformers zhkeybert keybert jieba requests
  !pip install pymongo

try:
  import jieba
  import os
  import snownlp
  import re
  import json
  import time
  import transformers
  import threading
  import requests
  import queue
  import pandas as pd
  from pyspark.sql import SparkSession
  from snownlp import SnowNLP
  from pymongo import MongoClient
  from transformers import pipeline
  from stopwords import stopwords, filter_stopwords
  from sentence_transformers import SentenceTransformer
  from sklearn.feature_extraction.text import CountVectorizer
  from concurrent.futures import ThreadPoolExecutor, as_completed
  # Compatible with zhkeybert and the new version of scikit-learn
  if not hasattr(CountVectorizer, "get_feature_names"):
      CountVectorizer.get_feature_names = CountVectorizer.get_feature_names_out

  from zhkeybert import KeyBERT
except Exception as e:
  print(e)
  install_library()
  import jieba
  import os
  import snownlp
  import re
  import json
  import time
  import transformers
  import threading
  import requests
  import queue
  import pandas as pd
  from pyspark.sql import SparkSession
  from snownlp import SnowNLP
  from pymongo import MongoClient
  from transformers import pipeline
  from stopwords import stopwords, filter_stopwords
  from sentence_transformers import SentenceTransformer
  from sklearn.feature_extraction.text import CountVectorizer
  from concurrent.futures import ThreadPoolExecutor, as_completed
  # Compatible with zhkeybert and the new version of scikit-learn
  if not hasattr(CountVectorizer, "get_feature_names"):
      CountVectorizer.get_feature_names = CountVectorizer.get_feature_names_out

  from zhkeybert import KeyBERT

/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
  re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
  re_skip_default = re.compile("(\r\n|\s)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
  re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")

No module named 'snownlp'
Collecting stopwords-zh
  Downloading stopwords_zh-2023.6.5.13.18.38-py3-none-any.whl.metadata (1.8 kB)
Downloading stopwords_zh-2023.6.5.13.18.38-py3-none-any.whl (39 kB)
Installing collected packages: stopwords-zh
Successfully installed stopwords-zh-2023.6.5.13.18.38
Collecting snownlp
  Downloading snownlp-0.12.3.tar.gz (37.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.6/37.6 MB 7.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: snownlp
  Building wheel for snownlp (setup.py) ... done
  Created wheel for snownlp: filename=snownlp-0.12.3-py3-none-any.whl size=37760946 sha256=cd7e7df42011e45bf4f04b9a00dca654fb9d30b6dcd9773c98e57d83f4b2a422
  Stored in directory: /root/.cache/pip/wheels/8a/0a/37/f15b8568f5463f1427466f701e9d3ba514035eb703f885efee
Successfully built snownlp
Installing collected packages: snownlp
Successfully installed snownlp-0.12.3
Requirement already satisfied: jieba in /usr/local/lib/python3.12/dist-packages (0.42.1)
Requirement already satisfied: Pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from Pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from Pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from Pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from Pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->Pandas) (1.17.0)
ERROR: Could not find a version that satisfies the requirement transsformers (from versions: none)
ERROR: No matching distribution found for transsformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 4.3 MB/s eta 0:00:00
Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 48.3 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 33.1 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0

## Loading the model

In [2]:
# Sentiment score distribution, specifically 1-5 stars, and confidence level.
emotional_5_star = pipeline("sentiment-analysis",
                            model="nlptown/bert-base-multilingual-uncased-sentiment")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [3]:
# Sentiment score distribution, specifically positive, negative, neutral,
# and confidence level.
emotional_3_value = pipeline("sentiment-analysis",
                             model="cardiffnlp/twitter-xlm-roberta-base-sentiment")

config.json:   0%|          | 0.00/841 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [4]:
# Chinese Keyword Extraction
kw_model = KeyBERT(model=
                   SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2"))

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:
# Spam comment judgment (LABEL_0: GARBAGE, LABEL_1: REGULAR)
garbage = pipeline("text-classification",
                   model="Titeiiko/OTIS-Official-Spam-Model")

config.json:   0%|          | 0.00/710 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/41 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [6]:
# Malicious insult comments (LABEL_0: REGULAR, LABEL_1: ABUSE)
garbage2 = pipeline("text-classification",
                    model="textdetox/xlmr-large-toxicity-classifier-v2")

config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

In [7]:
# Spam advertising monitoring (LABEL_0: REGULAR, LABEL_1: SPAM)
garbage3 = pipeline("text-classification",
                    model="mrm8488/bert-tiny-finetuned-sms-spam-detection")

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/17.6M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/41 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: mrm8488/bert-tiny-finetuned-sms-spam-detection
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/324 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [8]:
# Spam advertising monitoring (SPAM: SPAN, REGULAR:REGULAR, GIBBERISH: GIBBERISH)
garbage4 = pipeline("text-classification",
                    model="baptistejamin/xlm-roberta-large-spam_v4")

config.json:   0%|          | 0.00/977 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

## Constant settings

In [ ]:
# Mongo DB setting
CLIENT = "mongodb+srv://dbUser:password111@cluster0.zpnwntx.mongodb.net/?appName=Cluster0"
DEFAULT_DB = "Cluster0"

# Classification Tags setting
DEFAULT_CANDIDATE_LABELS = ["演员", "剧情", "情怀"]

# Fine-tuning keywords setting
positive_patterns = [
    r"无理由五星",r"五星",r"五分",r"满分",r"看了\d+次不嫌多",r"看了N次不嫌多",r"不嫌多",
    r"二刷",r"三刷",r"刷了好多遍",r"越看越上头",r"上头",r"封神",r"强烈推荐",r"值得看",r"值得二刷",
    r"好看到爆",r"太好看了",r"四星",r"四点五星",r"笑死",r"泪流满面",r"看不厌",r"治愈",r"笑崩了",
    r"停不下来","感动",r"哭死",r"哭瞎",r"泪奔",r"牛逼",r"不错"
    ]

negative_patterns = [
        r"浪费时间",r"看不下去",r"太烂了",r"烂尾",r"尴尬",r"无聊",r"不好看",r"不推荐",r"失望",
        r"差评",r"煎熬",r"偷懒"
    ]




TOPIC_MODEL_CONFIGS = [
    {
        "name": "deepseek/deepseek-chat",
        "base_url": "https://api.deepseek.com/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "deepseek-chat",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 20
    },
    {
        "name": "alibaba/deepseek-v3.2-exp",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "deepseek-v3.2-exp",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 10
    },
     {
        "name": "alibaba/kimi-k2.5",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "kimi-k2.5",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 8
    },
     {
        "name": "alibaba/MiniMax-M2.5",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "MiniMax-M2.5",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 8
    },
    {
        "name": "alibaba/deepseek-v3.1",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "deepseek-v3.1",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 8
    },
    {
        "name": "alibaba/qwen-turbo-latest",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "qwen-turbo-latest",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 8
    },
    {
        "name": "alibaba/qwen-turbo",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "qwen-turbo",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 8
    },
    {
        "name": "moonshot/kimi-k2-turbo-preview",
        "base_url": "https://api.moonshot.cn/v1",
        "path": "/chat/completions",
        "api_token": "sk",
        "model_name": "kimi-k2-turbo-preview",
        "timeout": 60,
        "max_retries": 3,
        "thread_workers": 3
    }
]

LLM_CHAT_COMPLETIONS_PATH = "/chat/completions"
LLM_TIMEOUT = 60
LLM_MAX_RETRIES = 3

# LLM setting
LLM_BASE_URL = "https://api.deepseek.com/v1"
LLM_CHAT_COMPLETIONS_PATH = "/chat/completions"
LLM_API_TOKEN = "sk"
LLM_MODEL_NAME = "deepseek-chat"

LLM_TIMEOUT = 60
LLM_MAX_RETRIES = 3
LLM_THREAD_WORKERS = 8

# Emotional scoring weighting settings
DEFAULT_W_STAR = 0.6
DEFAULT_W_TRI = 0.4

DEFAULT_LOW_CONF_THRESHOLD = 0.35
DEFAULT_CONFIDENCE_GAP_THRESHOLD = 0.25

DEFAULT_SENTENCE_BATCH_SIZE = 64
DEFAULT_TOPIC_BATCH_SIZE = 20
DEFAULT_MAX_CHARS = 120

## Testing LLM API

In [10]:
# Testing LLM API

def build_llm_prompt(comment):
    return f"""
你是一个中文影视评论情绪分类助手。

请判断下面这条评论的整体情绪倾向，只能从这三个标签里选一个：
positive / neutral / negative

判断标准：
- positive：整体明确偏赞扬、推荐、喜欢、认可
- neutral：客观描述、中性表达、信息不足、褒贬不明显
- negative：整体明确偏批评、不满、否定、吐槽

注意：
1. 结合中文日常表达、影视评论语境、网络语气
2. 像“无理由五星”“看了N次不嫌多”“值得二刷”“越看越上头”通常偏 positive
3. 不要把轻微吐槽、普通评价、客观描述轻易判成 negative
4. 只返回 JSON，不要输出任何额外文字

输出格式：
{{"label":"positive","reason":"一句话理由"}}

评论：
{comment}
""".strip()


def parse_llm_output(raw_output):
    raw_output = str(raw_output).strip()

    try:
        obj = json.loads(raw_output)
        label = str(obj.get("label", "")).strip().lower()
        reason = str(obj.get("reason", "")).strip()

        if label not in ["positive", "neutral", "negative"]:
            return {
                "llm_label": "negative",
                "llm_reason": f"The label is incorrect; the default is negative. Original output: {raw_output}",
                "llm_raw_output": raw_output
            }

        return {
            "llm_label": label,
            "llm_reason": reason,
            "llm_raw_output": raw_output
        }

    except Exception:
        match = re.search(r'"label"\s*:\s*"?(positive|neutral|negative)"?', raw_output, flags=re.IGNORECASE)
        if match:
            label = match.group(1).lower()
            return {
                "llm_label": label,
                "llm_reason": "Non-standard JSON, regular expression extraction successful.",
                "llm_raw_output": raw_output
            }

        return {
            "llm_label": "negative",
            "llm_reason": "JSON parsing failed; default fallback is negative.",
            "llm_raw_output": raw_output
        }


def call_llm_api(prompt):
    url = LLM_BASE_URL.rstrip("/") + LLM_CHAT_COMPLETIONS_PATH

    headers = {
        "Authorization": f"Bearer {LLM_API_TOKEN}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": LLM_MODEL_NAME,
        "messages": [
            {"role": "system", "content": "You are a rigorous sentiment classification assistant for Chinese film and TV reviews."},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0
    }

    last_error = None
    max_retries = globals().get("LLM_MAX_RETRIES", 3)
    timeout = globals().get("LLM_TIMEOUT", 60)

    for attempt in range(max_retries):
        try:
            resp = requests.post(
                url,
                headers=headers,
                json=payload,
                timeout=timeout
            )
            resp.raise_for_status()
            data = resp.json()
            return data["choices"][0]["message"]["content"]
        except Exception as e:
            last_error = e
            time.sleep(1.5 * (attempt + 1))

    raise RuntimeError(f"LLM request failed: {last_error}")


def review_single_negative_comment(comment):
    prompt = build_llm_prompt(comment)
    raw_output = call_llm_api(prompt)
    return parse_llm_output(raw_output)


test_comment = "看了N次不嫌多"
result = review_single_negative_comment(test_comment)
print(result)

{'llm_label': 'positive', 'llm_reason': '评论表达了反复观看的喜爱和高度认可', 'llm_raw_output': '{"label":"positive","reason":"评论表达了反复观看的喜爱和高度认可"}'}

## Data Base Tool function

### Spark Conneect

In [11]:
def connect_spark(mongo_uri, app_name="MongoSparkApp"):
    """
    Connect to Spark
    """
    spark = (
      SparkSession.builder
      .appName("MongoSparkApp")
      .config(
          "spark.jars.packages",
          "org.mongodb.spark:mongo-spark-connector_2.13:11.0.1"
      )
      .config("spark.mongodb.read.connection.uri", CLIENT)
      .config("spark.mongodb.write.connection.uri", CLIENT)
      .getOrCreate()
  )
    return spark


def ensure_spark_session(spark_or_uri, app_name="MongoSparkApp"):
    """
    It supports two data transmission methods:
    1. Passing a Mongo URI string,
    2. Passing a SparkSession object directly.
    """
    if isinstance(spark_or_uri, SparkSession):
        return spark_or_uri
    return connect_spark(spark_or_uri, app_name=app_name)


def build_mongo_uri_with_db(mongo_uri, db_name):
    """
    Build Mongo URI with DB name
    """
    return f"{mongo_uri.rstrip('/')}/{db_name}"

### Collection Basic Operations

In [12]:
def get_mongo_reader(spark, mongo_uri, db_name, collection_name):
    """
    GET Mongo reader
    """
    reader = (
        spark.read
        .format("mongodb")
        .option("uri", mongo_uri)
        .option("database", db_name)
        .option("collection", collection_name)
    )
    return reader


def get_mongo_writer(spark_df, mongo_uri, db_name, collection_name):
    """
    GET Mongo writer
    """
    writer = (
        spark_df.write
        .format("mongodb")
        .option("uri", mongo_uri)
        .option("database", db_name)
        .option("collection", collection_name)
    )
    return writer


def clear_collection(spark, mongo_uri, db_name, collection_name):
    """
    Clear a certain collection
    """
    empty_df = spark.createDataFrame([], "___dummy string")

    (
        get_mongo_writer(empty_df, mongo_uri, db_name, collection_name)
        .mode("overwrite")
        .save()
    )

    return 0

### Mongo DB to DataFrame

In [13]:
def load_mongo_to_dataframe(spark, mongo_uri, db_name, collection_name, query=None, projection=None):
    """
    Get data from Mongo DB and turn it into DataFrame
    """
    pipeline = []

    if query is not None and query != {}:
        pipeline.append({"$match": query})

    if projection is not None:
        pipeline.append({"$project": projection})

    reader = get_mongo_reader(spark, mongo_uri, db_name, collection_name)

    if pipeline:
        pipeline_str = str(pipeline).replace("'", '"')
        reader = reader.option("pipeline", pipeline_str)

    df = reader.load()
    return df


def insert_dataframe_to_collection(df, mongo_uri, db_name, collection_name, clear_first=True):
    """
    Write a DataFrame to a MongoDB collection.
    clear_first=True means clear the target table before writing.
    """
    if df is None:
        return 0

    if len(df.head(1)) == 0:
        return 0

    mode = "overwrite" if clear_first else "append"

    (
        get_mongo_writer(df, mongo_uri, db_name, collection_name)
        .mode(mode)
        .save()
    )

    return df.count()

### CSV Export

In [14]:
def export_dataframe_to_csv(df, output_csv_path, encoding="utf-8"):
    """
    Export DataFrame to CSV
    """
    temp_dir = output_csv_path + "_spark_tmp"

    (
        df.coalesce(1)
        .write
        .mode("overwrite")
        .option("header", "true")
        .option("encoding", encoding)
        .csv(temp_dir)
    )

    part_file = None
    for file_name in os.listdir(temp_dir):
        if file_name.startswith("part-") and file_name.endswith(".csv"):
            part_file = os.path.join(temp_dir, file_name)
            break

    if part_file is None:
        raise FileNotFoundError(f"No CSV file generated in {temp_dir}")

    os.replace(part_file, output_csv_path)

    for file_name in os.listdir(temp_dir):
        file_path = os.path.join(temp_dir, file_name)
        if os.path.isfile(file_path):
            os.remove(file_path)

    os.rmdir(temp_dir)

def build_csv_path_from_collection_name(
    collection_name,
    output_dir="/content"):
    """
    Generate a CSV file with the same name based on the collection name.
    """
    return f"{output_dir}/{collection_name}.csv"

### CSV File Helper Functions

In [15]:
def normalize_csv_files(csv_files):
    """
    Compatibility with single string and list of multiple files
    """
    if isinstance(csv_files, str):
        return [csv_files]
    return list(csv_files)


def read_csv_columns(spark, csv_file, encoding="utf-8"):
    """
    Read only CSV header fields
    """
    df_head = (
        spark.read
        .option("header", "true")
        .option("inferSchema", "false")
        .option("encoding", encoding)
        .csv(csv_file)
    )
    return list(df_head.columns)


def get_collection_name_from_csv_file(csv_file):
    """
    Generate collection names based on filenames
    """
    base_name = os.path.basename(csv_file)
    file_name_without_ext = os.path.splitext(base_name)[0]
    return file_name_without_ext

### CSV Writing to MongoDB by Spark

In [16]:
def insert_csv_to_collection(spark, csv_file, mongo_uri, db_name, collection_name, encoding="utf-8", mode="append"):
    """
    Write a CSV file to a collection
    """
    df = (
        spark.read
        .option("header", "true")
        .option("inferSchema", "true")
        .option("encoding", encoding)
        .csv(csv_file)
    )

    if len(df.head(1)) == 0:
        return 0

    (
        get_mongo_writer(df, mongo_uri, db_name, collection_name)
        .mode(mode)
        .save()
    )

    return df.count()


def import_one_csv_to_one_collection(
    csv_file,
    spark,
    db_name,
    collection_name,
    chunk_size=1000,
    encoding="utf-8"
):
    """
    Importing a collection from a single CSV file
    """
    inserted_total = insert_csv_to_collection(
        spark=spark,
        csv_file=csv_file,
        mongo_uri=spark.conf.get("spark.mongodb.write.connection.uri"),
        db_name=db_name,
        collection_name=collection_name,
        encoding=encoding,
        mode="append"
    )

    return inserted_total

### Single / Multiple CSV import into MongoDB

In [17]:
def csv_to_mongodb_in_chunks(
    csv_files,
    mongo_uri_or_spark,
    db_name,
    collection_name=None,
    chunk_size=1000,
    encoding="utf-8",
    split_mode=0,
    clear_mode=0
):
    """
    Supports batch import of single or multiple CSV files into MongoDB

    Parameters:
    - encoding:
      File encoding.
    - split_mode:
      1 = Force partitioning (partition by filename).
      0 = Check fields.
      * Same fields -> Merge vertically into collection_name.
      * Different fields -> Automatically partition by filename and issue a warning.
    - clear_mode:
      1 = Clear the target collection before importing.
      0 = Do not clear, append directly.
    """
    spark = ensure_spark_session(mongo_uri_or_spark)
    mongo_uri = spark.conf.get("spark.mongodb.write.connection.uri")
    csv_files = normalize_csv_files(csv_files)

    if not csv_files:
        print("No CSV file is available for import.")
        return

    # Single file
    if len(csv_files) == 1:
        target_collection_name = collection_name or get_collection_name_from_csv_file(csv_files[0])

        mode = "overwrite" if clear_mode == 1 else "append"

        inserted_count = insert_csv_to_collection(
            spark=spark,
            csv_file=csv_files[0],
            mongo_uri=mongo_uri,
            db_name=db_name,
            collection_name=target_collection_name,
            encoding=encoding,
            mode=mode
        )

        print(f"{csv_files[0]} import complete, collection: {target_collection_name}, total insertion {inserted_count}.")
        return

    # Multiple files and forced table partitioning
    if split_mode == 1:
        total_inserted = 0

        for csv_file in csv_files:
            target_collection_name = get_collection_name_from_csv_file(csv_file)
            mode = "overwrite" if clear_mode == 1 else "append"

            inserted_count = insert_csv_to_collection(
                spark=spark,
                csv_file=csv_file,
                mongo_uri=mongo_uri,
                db_name=db_name,
                collection_name=target_collection_name,
                encoding=encoding,
                mode=mode
            )

            total_inserted += inserted_count
            print(f"{csv_file} import complete, collection: {target_collection_name}, total insertion {inserted_count}.")

        print(f"All files were imported in separate tables by filename, with a total of {total_inserted} inserts.")
        return

    # Multiple files
    # split_mode=0: Check if fields are consistent
    column_map = {}
    for csv_file in csv_files:
        column_map[csv_file] = read_csv_columns(spark, csv_file, encoding=encoding)

    first_file = csv_files[0]
    first_columns = column_map[first_file]

    all_same_columns = all(column_map[f] == first_columns for f in csv_files)

    # Fields are consistent: Vertical merger
    if all_same_columns:
        if not collection_name:
            raise ValueError("When multiple csv file merge in one collection, collection_name must be passed in.")

        df = (
            spark.read
            .option("header", "true")
            .option("inferSchema", "true")
            .option("encoding", encoding)
            .csv(csv_files)
        )

        mode = "overwrite" if clear_mode == 1 else "append"

        (
            get_mongo_writer(df, mongo_uri, db_name, collection_name)
            .mode(mode)
            .save()
        )

        total_inserted = df.count()
        print(f"All file fields are consistent and have been vertically merged in {collection_name}, with a total of {total_inserted} inserts.")
        return

    # Different fields: Automatic table partitioning and warning
    print("WARNING: Cause of the fields, automatic table partitioning.")

    total_inserted = 0

    for csv_file in csv_files:
        target_collection_name = get_collection_name_from_csv_file(csv_file)
        mode = "overwrite" if clear_mode == 1 else "append"

        inserted_count = insert_csv_to_collection(
            spark=spark,
            csv_file=csv_file,
            mongo_uri=mongo_uri,
            db_name=db_name,
            collection_name=target_collection_name,
            encoding=encoding,
            mode=mode
        )

        total_inserted += inserted_count
        print(f"{csv_file} import complete, collection: {target_collection_name}, total insertion {inserted_count}.")

    print(f"Due to the different fields, the import has been automatically completed by splitting the data into separate tables according to filenames, and a total of {total_inserted} records have been inserted.")

### Export all table in the entire database to CSV

In [18]:

def list_collection_names(mongo_uri, db_name):
    """
    Get all collection names in DB
    """
    client = MongoClient(mongo_uri)
    try:
        return client[db_name].list_collection_names()
    finally:
        client.close()


def export_all_collections_to_csv(
    mongo_uri_or_spark,
    db_name,
    output_dir="/content",
    encoding="utf-8",
    drop_id=True
):
    """
    Iterate through all collections in the entire database,
    and export them as CSV files by table name.
    """
    spark = ensure_spark_session(mongo_uri_or_spark)

    if isinstance(mongo_uri_or_spark, str):
        mongo_uri = mongo_uri_or_spark
    else:
        mongo_uri = spark.conf.get("spark.mongodb.read.connection.uri")

    os.makedirs(output_dir, exist_ok=True)

    collection_names = list_collection_names(
        mongo_uri=mongo_uri,
        db_name=db_name
    )

    if not collection_names:
        print(f"No collection in {db_name} DB.")
        return []

    exported_files = []

    for collection_name in collection_names:
        try:
            df = load_mongo_to_dataframe(
                spark=spark,
                mongo_uri=mongo_uri,
                db_name=db_name,
                collection_name=collection_name,
                query={},
                projection=None
            )

            if len(df.head(1)) == 0:
                print(f"No data in {collection_name} collection, skip.")
                continue

            if drop_id and "_id" in df.columns:
                df = df.drop("_id")

            output_csv_path = build_csv_path_from_collection_name(
                collection_name=collection_name,
                output_dir=output_dir
            )

            export_dataframe_to_csv(
                df=df,
                output_csv_path=output_csv_path,
                encoding=encoding
            )

            exported_files.append(output_csv_path)
            print(f"{collection_name} export success: {output_csv_path}, total {df.count()} rows.")

        except Exception as e:
            print(f"{collection_name} export failed: {e}")

    print(f"All export finished, total {len(exported_files)} CSV files.")
    return exported_files

### For DEBUG

In [19]:
# Stop the spark
try:
    spark.stop()
except:
    pass

In [20]:
# Re-make spark Connection
spark = (
    SparkSession.builder
    .appName("MongoSparkApp")
    .config(
        "spark.jars.packages",
        "org.mongodb.spark:mongo-spark-connector_2.13:11.0.1"
    )
    .config("spark.mongodb.read.connection.uri", CLIENT)
    .config("spark.mongodb.write.connection.uri", CLIENT)
    .getOrCreate()
)

In [21]:
# GET spark version
print("Spark version:", spark.version)
print("Scala version:", spark._jvm.scala.util.Properties.versionNumberString())

Spark version: 4.0.2
Scala version: 2.13.16

In [22]:
# Test
test_df = (
    spark.read
    .format("mongodb")
    .option("database", DEFAULT_DB)
    .option("collection", "dws_douban_comment")
    .load()
)

test_df.show(5)

+--------------------+----------------------------------------+------+-------+----------+
|                 _id|                                 comment|season|user_id| user_name|
+--------------------+----------------------------------------+------+-------+----------+
|69c76423f39621205...|       跟从前一样，喜欢死了。（2022）...|     1|     22|         P|
|69c76423f39621205...|心头挚爱，不能忘怀，将伴我与我之挚爱终生|     1|     43|      神威|
|69c76423f39621205...|    1集弃（煎熬），生活大爆炸好看太多...|     1|     83|从小爱看剧|
|69c76423f39621205...|   挺搞笑的，台词轻松幽默，比较贴近生...|     1|     97|      宁宁|
|69c76423f39621205...|                看见你们，就是好的时光。|     1|     33|      草威|
+--------------------+----------------------------------------+------+-------+----------+
only showing top 5 rows

## Overall process

| Step | Remarks | Name |
| :---: | --- | --- |
| Regex pre-screening | Filter out entries that are too short, only symbols, empty, purely numeric, or duplicates | *DWS_comment_rule_filtered* |
| Model fine-filtering | Filter out advertisements, irrelevant, and garbage comments | *DWS_comment_model_filtered* |
| Text preprocessing | Split comments into sentences, tokenize, remove stopwords, drop invalid short sentences, and join processed text | *DWS_comment_preprocessed* |
| Sentiment analysis | Perform sentiment and keyword analysis on comments | *DWS_comment_sentiment_analysis* |
| Topic analysis | Perform topic classification on comments | *DWS_comment_topic_analysis* |
| Merge sentiment and topic | Enrich/complete fields by merging results | *ADS_comment_theme_analysis* |
| Seasonal aggregation | Finalize/complete seasonal-level fields | *ADS_season_overall_evaluation* |

## Regex pre-screening
Filter out nulls, blanks, pure symbols, pure numbers, overly short comments, and duplicate comments.

- Duplicate comments:
    | Type | Action |
    | -- | -- |
    | Same season, same user comments (regardless of whether the content is identical) | Keep the longer comment; if lengths are equal, keep the newer one. |
    | Same season, different users with identical content | Keep only one entry. |
    | Different seasons, identical content (regardless of user) | Delete all occurrences. |

In [23]:
# Data pre-screening
# The purpose is to filter out some obviously low-quality comments before the formal cleaning and LLM review,
#  to improve the overall efficiency and reduce the cost of LLM review.
# Output collection: dws_comment_rule_filtered


# Comment cleaning basic function area

def remove_null_comments(df, comment_col="comment"):
    """
    Remove lines where the comment is empty.
    """
    return df[df[comment_col].notna()].copy()


def strip_comment_whitespace(df, comment_col="comment"):
    """
    Remove leading and trailing spaces from comments
    """
    new_df = df.copy()
    new_df[comment_col] = new_df[comment_col].astype(str).str.strip()
    return new_df


def remove_blank_comments(df, comment_col="comment"):
    """
    Remove empty string comments
    """
    return df[df[comment_col] != ""].copy()


def is_all_symbol(text):
    """
    Determine if it is a pure symbol
    """
    text = str(text).strip()
    return not bool(re.search(r"[\u4e00-\u9fffA-Za-z0-9]", text))


def remove_symbol_only_comments(df, comment_col="comment"):
    """
    Remove pure symbol comments
    """
    return df[~df[comment_col].apply(is_all_symbol)].copy()


def is_all_number(text):
    """
    Determine if it is a pure number
    """
    text = str(text).strip()
    return bool(re.fullmatch(r"\d+", text))


def remove_number_only_comments(df, comment_col="comment"):
    """
    Remove purely numerical comments
    """
    return df[~df[comment_col].apply(is_all_number)].copy()


def remove_short_comments(df, min_length=2, comment_col="comment"):
    """
    Remove overly short comments
    """
    return df[df[comment_col].str.len() >= min_length].copy()


def drop_duplicate_comments(df, comment_col="comment", keep="first"):
    """
    Deduplication of regular duplicate comments
    """
    return df.drop_duplicates(subset=[comment_col], keep=keep).copy()


# Comment and username normalization functions

def normalize_comment_text(text, remove_punctuation=False):
    """
    Standardized Comments:

    Remove leading and trailing spaces
    Remove all whitespace characters
    Optional: Remove punctuation
    """
    text = str(text).strip()
    text = re.sub(r"\s+", "", text)

    if remove_punctuation:
        text = re.sub(r"[^\u4e00-\u9fffA-Za-z0-9]", "", text)

    return text


def add_normalized_comment_column(
    df,
    comment_col="comment",
    new_col="comment_clean",
    remove_punctuation=False
):
    """
    Added standardized comment column
    """
    new_df = df.copy()
    new_df[new_col] = new_df[comment_col].apply(
        lambda x: normalize_comment_text(x, remove_punctuation=remove_punctuation)
    )
    return new_df


def normalize_username_text(text):
    """
    Standardized Username:

    Remove leading and trailing spaces
    Compress consecutive spaces into a single space
    """
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    return text


def add_normalized_username_column(
    df,
    username_col="user_name",
    new_col="user_name_clean"
):
    """
    Added standardized user list
    """
    new_df = df.copy()
    new_df[new_col] = new_df[username_col].apply(normalize_username_text)
    return new_df


# Deduplication rule function area

def deduplicate_same_season_same_user(
    df,
    season_col="season",
    username_col="user_name_clean",
    comment_col="comment_clean"
):
    """
    Rule 1:

    For comments posted in the same season and by the same username
    (regardless of whether the comments are identical),
    the longer comment will be used. If the lengths are the same,
    the later comment from the original data will be used.
    """
    new_df = df.copy()
    new_df["_row_order"] = range(len(new_df))
    new_df["_comment_len"] = new_df[comment_col].str.len()

    new_df = (
        new_df.sort_values(
            by=[season_col, username_col, "_comment_len", "_row_order"],
            ascending=[True, True, False, False]
        )
        .drop_duplicates(subset=[season_col, username_col], keep="first")
        .copy()
    )

    new_df = new_df.drop(columns=["_row_order", "_comment_len"])
    return new_df


def deduplicate_same_season_same_comment(
    df,
    season_col="season",
    comment_col="comment_clean"
):
    """
    Rule 2:

    If comments posted by different users in the same season have the same content,
    only one will be retained.
    """
    return df.drop_duplicates(subset=[season_col, comment_col], keep="first").copy()


def remove_cross_season_same_comments(
    df,
    season_col="season",
    comment_col="comment_clean"
):
    """
    Rule 3:

    Identical comments across different seasons (regardless of user affiliation)
    Delete all
    """
    new_df = df.copy()

    cross_season_comments = (
        new_df.groupby(comment_col)[season_col]
        .nunique()
    )

    cross_season_comments = cross_season_comments[cross_season_comments > 1].index

    new_df = new_df[~new_df[comment_col].isin(cross_season_comments)].copy()
    return new_df


# Clean the total function area

def clean_comments_basic(
    df,
    username_col="user_name",
    comment_col="comment",
    min_length=2,
    remove_punctuation=False
):
    """
    Basic Cleaning:

    1. Remove null values from comment
    2. Remove null values from user_name
    3. Remove leading and trailing spaces
    4. Generate a standardized comment column
    5. Generate a standardized username column
    6. Remove blank comments
    7. Remove comments consisting solely of symbols
    8. Remove comments consisting solely of numbers
    9. Remove excessively short comments
    """
    new_df = df.copy()

    new_df = new_df[new_df[comment_col].notna()].copy()
    new_df = new_df[new_df[username_col].notna()].copy()

    new_df = strip_comment_whitespace(new_df, comment_col=comment_col)

    new_df[username_col] = new_df[username_col].astype(str).str.strip()
    new_df = new_df[new_df[username_col] != ""].copy()

    new_df = add_normalized_comment_column(
        new_df,
        comment_col=comment_col,
        new_col="comment_clean",
        remove_punctuation=remove_punctuation
    )

    new_df = add_normalized_username_column(
        new_df,
        username_col=username_col,
        new_col="user_name_clean"
    )

    new_df = remove_blank_comments(new_df, comment_col=comment_col)
    new_df = remove_symbol_only_comments(new_df, comment_col=comment_col)
    new_df = remove_number_only_comments(new_df, comment_col=comment_col)
    new_df = remove_short_comments(new_df, min_length=min_length, comment_col="comment_clean")

    return new_df


def apply_comment_dedup_rules(
    df,
    season_col="season",
    username_col="user_name_clean",
    comment_col="comment_clean"
):
    """
    Follow three rules
    """
    new_df = deduplicate_same_season_same_user(
        df,
        season_col=season_col,
        username_col=username_col,
        comment_col=comment_col
    )

    new_df = deduplicate_same_season_same_comment(
        new_df,
        season_col=season_col,
        comment_col=comment_col
    )

    new_df = remove_cross_season_same_comments(
        new_df,
        season_col=season_col,
        comment_col=comment_col
    )

    return new_df


def process_comment_dataframe(
    df,
    season_col="season",
    username_col="user_name",
    comment_col="comment",
    min_length=2,
    remove_punctuation=False,
    final_drop_duplicates=True,
    keep_clean_columns=False
):
    """
    Only handle DataFrame
    """
    new_df = df.copy()

    required_cols = [season_col, username_col, comment_col]
    missing_cols = [col for col in required_cols if col not in new_df.columns]
    if missing_cols:
        raise ValueError(f"Missing field: {missing_cols}")

    if "_id" in new_df.columns:
        new_df = new_df.drop(columns=["_id"])

    new_df[season_col] = pd.to_numeric(new_df[season_col], errors="coerce")
    new_df = new_df[new_df[season_col].notna()].copy()
    new_df[season_col] = new_df[season_col].astype(int)

    new_df = clean_comments_basic(
        new_df,
        username_col=username_col,
        comment_col=comment_col,
        min_length=min_length,
        remove_punctuation=remove_punctuation
    )

    new_df = apply_comment_dedup_rules(
        new_df,
        season_col=season_col,
        username_col="user_name_clean",
        comment_col="comment_clean"
    )

    if final_drop_duplicates:
        new_df = drop_duplicate_comments(
            new_df,
            comment_col="comment_clean",
            keep="first"
        )

    if not keep_clean_columns:
        new_df = new_df.drop(columns=["comment_clean", "user_name_clean"], errors="ignore")

    return new_df


# All

def run_comment_cleaning_pipeline(
    mongo_uri,
    source_db,
    source_collection,
    target_db,
    target_collection,
    output_csv_path,
    season_col="season",
    username_col="user_name",
    comment_col="comment",
    min_length=2,
    remove_punctuation=False,
    final_drop_duplicates=True,
    keep_clean_columns=False,
    csv_encoding="utf-8",
    clear_target_first=True
):
    spark = connect_spark(mongo_uri)

    source_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=source_collection,
        query={},
        projection={"_id": 0}
    )

    source_df = source_spark_df.toPandas()

    result_df = process_comment_dataframe(
        df=source_df,
        season_col=season_col,
        username_col=username_col,
        comment_col=comment_col,
        min_length=min_length,
        remove_punctuation=remove_punctuation,
        final_drop_duplicates=final_drop_duplicates,
        keep_clean_columns=keep_clean_columns
    )

    result_spark_df = spark.createDataFrame(result_df)

    inserted_count = insert_dataframe_to_collection(
        df=result_spark_df,
        mongo_uri=mongo_uri,
        db_name=target_db,
        collection_name=target_collection,
        clear_first=clear_target_first
    )

    export_dataframe_to_csv(
        df=result_spark_df,
        output_csv_path=output_csv_path,
        encoding=csv_encoding
    )

    print(f"Original: {len(source_df)}")
    print(f"After cleaning: {len(result_df)}")
    print(f"Write new collection success: {inserted_count}")
    print(f"CSV Export success: {output_csv_path}")

    return result_df


# Main

result = run_comment_cleaning_pipeline(
    mongo_uri=CLIENT,
    source_db=DEFAULT_DB,
    source_collection="dws_douban_comment",
    target_db=DEFAULT_DB,
    target_collection="dws_comment_rule_filtered",
    output_csv_path="DWS_comment_rule_filtered.csv",
    season_col="season",
    username_col="user_name",
    comment_col="comment",
    min_length=2,
    remove_punctuation=False,
    final_drop_duplicates=True,
    keep_clean_columns=False,
    csv_encoding="utf-8",
    clear_target_first=True
)

result.head()

Original: 3999
After cleaning: 3552
Write new collection success: 3552
CSV Export success: DWS_comment_rule_filtered.csv

,comment,season,user_id,user_name
290,也算是慢热的作品 开始补经典老剧 第一感觉是没那么好笑也没那么出彩 很多套路已经看到了结局 ...,1,166,1624
59,看过的最长的也是最值得的电视剧,1,173,2ric
210,结束了，可是我该去哪里呢？,1,382,"404,Not Found"
394,经典。,1,91,83。
357,用十几天的时间穿越了整整十年。或许是因为时间过短，对于一些让多数人流泪的回忆镜头，对我来说，...,1,396,????

## Delete irrelevant comments
Delete some un-important comments just like spam / gibberish comment

| Process Step | Description |
|---|---|
| Read comment data | Read the comments to be processed from MongoDB |
| Batch detection with 4 models | Each comment is analyzed for anomaly pre-screening, aggressiveness detection, advertisement detection, and normality detection |
| Label translation | Convert the model labels into human-readable results |
| Convert to keep scores | Transform the outputs of Models 2, 3, and 4 into unified “keep tendency scores” |
| Weighted fusion | Calculate the final score using `0.2*k2 + 0.35*k3 + 0.45*k4` |
| Veto mechanism | If Model 1 detects an anomaly, the final score is directly set to 0 |
| Threshold decision | Keep the comment if the final score ≥ 0.6; otherwise, filter it out |
| Output results | Write the retained data into a new collection and export it as a CSV file |

In [24]:
# Delete the irrelevant comments
# Output collection: dws_comment_model_filtered

# Scoring-related functions

def translate_model_labels(label1, label2_, label3, label4):
    model1_tag = "Pre-existing anomalies/suspicious conditions" if label1 == "LABEL_0" else "Pre-engine normal"
    model2_tag = "Neutral/normal criticism" if label2_ == "LABEL_0" else "Negative attack/critical tendency"
    model3_tag = "Non-advertisement" if label3 == "LABEL_0" else "Advertisement/traffic diversion"

    if label4 == "regular":
        model4_tag = "Normal comment"
    elif label4 == "spam":
        model4_tag = "Spam advertisement"
    elif label4 == "gibberish":
        model4_tag = "Gibberish/flooding"
    else:
        model4_tag = label4

    return model1_tag, model2_tag, model3_tag, model4_tag


def calculate_keep_score(label2_, score2, label3, score3, label4, score4):
    # Model 2
    k2 = score2 if label2_ == "LABEL_0" else 1 - score2

    # Model 3
    k3 = score3 if label3 == "LABEL_0" else 1 - score3

    # Model 4
    k4 = score4 if label4 == "regular" else 1 - score4

    final_score = 0.2 * k2 + 0.35 * k3 + 0.45 * k4
    return k2, k3, k4, final_score


def decide_keep(label1, final_score, threshold=0.6):
    # Veto by the pre-model
    if label1 == "LABEL_0":
        final_score = 0

    keep = final_score >= threshold
    decision = "Keep" if keep else "Do not keep"
    return keep, decision, final_score

# Batch scoring function

def score_comments_with_models(
    df,
    garbage,
    garbage2,
    garbage3,
    garbage4,
    comment_col="comment",
    threshold=0.6,
    batch_size=32
):
    """
    Batch score the comment column in a DataFrame
    Return a new DataFrame with score columns added
    """
    new_df = df.copy()

    if comment_col not in new_df.columns:
        raise ValueError(f"Missing field: {comment_col}")

    new_df = new_df[new_df[comment_col].notna()].copy()
    new_df[comment_col] = new_df[comment_col].astype(str)

    # Preserve original order
    new_df = new_df.reset_index(drop=False).rename(columns={"index": "_original_index"})

    texts = new_df[comment_col].tolist()

    # Run 4 models in batch
    results1 = garbage(texts, batch_size=batch_size)
    results2 = garbage2(texts, batch_size=batch_size)
    results3 = garbage3(texts, batch_size=batch_size)
    results4 = garbage4(texts, batch_size=batch_size)

    rows = []

    for row_dict, r1, r2, r3, r4 in zip(new_df.to_dict("records"), results1, results2, results3, results4):
        label1, score1 = r1["label"], r1["score"]
        label2_, score2 = r2["label"], r2["score"]
        label3, score3 = r3["label"], r3["score"]
        label4, score4 = r4["label"], r4["score"]

        model1_tag, model2_tag, model3_tag, model4_tag = translate_model_labels(
            label1, label2_, label3, label4
        )

        k2, k3, k4, final_score = calculate_keep_score(
            label2_, score2, label3, score3, label4, score4
        )

        keep, decision, final_score = decide_keep(
            label1, final_score, threshold=threshold
        )

        row_dict.update({
            "label1": label1,
            "score1": score1,
            "model1_tag": model1_tag,

            "label2": label2_,
            "score2": score2,
            "model2_tag": model2_tag,
            "k2": k2,

            "label3": label3,
            "score3": score3,
            "model3_tag": model3_tag,
            "k3": k3,

            "label4": label4,
            "score4": score4,
            "model4_tag": model4_tag,
            "k4": k4,

            "final_score": final_score,
            "keep": keep,
            "decision": decision
        })

        rows.append(row_dict)

    scored_df = pd.DataFrame(rows)
    scored_df = scored_df.sort_values("_original_index").reset_index(drop=True)

    return scored_df

# DataFrame filtering function

def filter_dataframe_by_model_score(
    df,
    garbage,
    garbage2,
    garbage3,
    garbage4,
    comment_col="comment",
    threshold=0.6,
    batch_size=32,
    keep_score_columns=False
):
    """
    Score the DataFrame and keep only rows where keep=True
    """
    scored_df = score_comments_with_models(
        df=df,
        garbage=garbage,
        garbage2=garbage2,
        garbage3=garbage3,
        garbage4=garbage4,
        comment_col=comment_col,
        threshold=threshold,
        batch_size=batch_size
    )

    filtered_df = scored_df[scored_df["keep"]].copy()

    if not keep_score_columns:
        drop_cols = [
            "_original_index",
            "label1", "score1", "model1_tag",
            "label2", "score2", "model2_tag", "k2",
            "label3", "score3", "model3_tag", "k3",
            "label4", "score4", "model4_tag", "k4",
            "final_score", "keep", "decision"
        ]
        filtered_df = filtered_df.drop(columns=drop_cols, errors="ignore")

    return filtered_df, scored_df

# MongoDB read -> score and filter -> write to new table -> export CSV with same name

def run_model_score_filter_pipeline(
    mongo_uri,
    source_db,
    source_collection,
    target_db,
    target_collection,
    garbage,
    garbage2,
    garbage3,
    garbage4,
    comment_col="comment",
    threshold=0.6,
    batch_size=32,
    keep_score_columns=False,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
):
    """
    Read data from MongoDB, then after model scoring and filtering:
    1. Write into a new collection
    2. Export a CSV with the same name
    """
    spark = connect_spark(mongo_uri)

    source_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=source_collection,
        query={},
        projection={"_id": 0}
    )

    if len(source_spark_df.head(1)) == 0:
        print("The source collection has no data")
        return pd.DataFrame(), pd.DataFrame()

    source_df = source_spark_df.toPandas()

    filtered_df, scored_df = filter_dataframe_by_model_score(
        df=source_df,
        garbage=garbage,
        garbage2=garbage2,
        garbage3=garbage3,
        garbage4=garbage4,
        comment_col=comment_col,
        threshold=threshold,
        batch_size=batch_size,
        keep_score_columns=keep_score_columns
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection,
        output_dir=output_dir
    )

    inserted_count = 0

    if not filtered_df.empty:
        filtered_spark_df = spark.createDataFrame(filtered_df)

        inserted_count = insert_dataframe_to_collection(
            df=filtered_spark_df,
            mongo_uri=mongo_uri,
            db_name=target_db,
            collection_name=target_collection,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=filtered_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No records retained after scoring")

    print(f"Source collection: {source_collection}")
    print(f"Number of source records: {len(source_df)}")
    print(f"Number of retained records after scoring: {len(filtered_df)}")
    print(f"New collection written successfully: {inserted_count} records")

    if not filtered_df.empty:
        print(f"CSV exported successfully: {output_csv_path}")

    return filtered_df, scored_df

# Pipeline invocation section

filtered_result, scored_result = run_model_score_filter_pipeline(
    mongo_uri=CLIENT,
    source_db=DEFAULT_DB,
    source_collection="dws_comment_rule_filtered",
    target_db=DEFAULT_DB,
    target_collection="dws_comment_model_filtered",
    garbage=garbage,
    garbage2=garbage2,
    garbage3=garbage3,
    garbage4=garbage4,
    comment_col="comment",
    threshold=0.6,
    batch_size=32,
    keep_score_columns=False,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
)

filtered_result.head()

Source collection: dws_comment_rule_filtered
Number of source records: 3552
Number of retained records after scoring: 2499
New collection written successfully: 2499 records
CSV exported successfully: /content/dws_comment_model_filtered.csv

,_id,comment,season,user_id,user_name
0,69d3b56ccfdfe064ff55fba8,也算是慢热的作品 开始补经典老剧 第一感觉是没那么好笑也没那么出彩 很多套路已经看到了结局 ...,1,166,1624
1,69d3b56ccfdfe064ff55fba9,看过的最长的也是最值得的电视剧,1,173,2ric
2,69d3b56ccfdfe064ff55fbaa,结束了，可是我该去哪里呢？,1,382,"404,Not Found"
3,69d3b56ccfdfe064ff55fbab,经典。,1,91,83。
4,69d3b56ccfdfe064ff55fbac,用十几天的时间穿越了整整十年。或许是因为时间过短，对于一些让多数人流泪的回忆镜头，对我来说，...,1,396,????

## Comment Text Preprocessing
This module is used to preprocess filtered comment data by splitting comments into sentences, tokenizing the text, removing stopwords and invalid tokens, filtering out short sentences, and generating cleaned comment text for downstream analysis.

| Process Step | Description |
|---|---|
| Read comment data | Read the filtered comment data from MongoDB |
| Field and null-value check | Check the `season` and `comment` fields and remove empty comments |
| Sentence splitting | Split each comment into sentences based on sentence-ending punctuation such as periods, question marks, exclamation marks, and semicolons |
| Sentence tokenization | Use `jieba` to tokenize each sentence |
| Stopword removal | Remove common stopwords that do not carry meaningful information |
| Invalid token cleaning | Remove blank tokens and tokens consisting only of symbols |
| Short sentence filtering | Remove sentences with fewer than 2 tokens after tokenization |
| Text reconstruction | Recombine valid sentences into a new `processed_comment` |
| Invalid result removal | Remove records whose processed results are empty |
| Save output | Write the results into a new MongoDB collection and export them as a CSV file |

In [25]:
# Split the comment into sentences, then tokenize and remove stopwords for each sentence, and finally join them together.
# Output collection: dws_comment_preprocessed


# Text preprocessing function section

def split_sentences(text):
    """
    Split text into sentences by sentence-ending punctuation:
    - Split by 。！？；.!?; … etc.
    - Do not split by commas
    - Compatible with both Chinese and English
    """
    if pd.isna(text):
        return []

    text = str(text).strip()
    if not text:
        return []

    sentences = re.split(r'[。！？!?；;…]+|\.(?=\s|$)', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    return sentences


def clean_tokens(tokens):
    """
    Clean tokenization results:
    - Remove blanks
    - Remove pure symbols
    """
    cleaned = []

    for token in tokens:
        token = str(token).strip()
        if not token:
            continue

        if re.fullmatch(r'[\W_]+', token, flags=re.UNICODE):
            continue

        cleaned.append(token)

    return cleaned


def process_single_sentence(sentence, min_tokens=2):
    """
    Process a single sentence:
    1. Tokenize with jieba
    2. Remove stopwords
    3. Clean invalid tokens
    4. Drop if too short
    """
    if not sentence:
        return None

    tokens = filter_stopwords(jieba.cut(sentence))
    tokens = list(tokens)
    tokens = clean_tokens(tokens)

    if len(tokens) < min_tokens:
        return None

    return "".join(tokens)


def process_comment_text(comment, min_tokens=2):
    """
    Process a single comment:
    Split into sentences -> tokenize and remove stopwords for each sentence -> remove invalid short sentences -> join
    """
    sentences = split_sentences(comment)

    processed_sentences = []
    for sentence in sentences:
        processed = process_single_sentence(sentence, min_tokens=min_tokens)
        if processed:
            processed_sentences.append(processed)

    return ".".join(processed_sentences)


def preprocess_comments_dataframe(
    df,
    season_col="season",
    comment_col="comment",
    min_tokens=2
):
    """
    Input a DataFrame and output only:
    season, comment, processed_comment
    """
    required_cols = [season_col, comment_col]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing fields: {missing_cols}")

    new_df = df[[season_col, comment_col]].copy()

    if "_id" in new_df.columns:
        new_df = new_df.drop(columns=["_id"])

    new_df = new_df[new_df[comment_col].notna()].copy()
    new_df[comment_col] = new_df[comment_col].astype(str).str.strip()
    new_df = new_df[new_df[comment_col] != ""].copy()

    new_df["processed_comment"] = new_df[comment_col].apply(
        lambda x: process_comment_text(x, min_tokens=min_tokens)
    )

    new_df = new_df[new_df["processed_comment"].notna()].copy()
    new_df["processed_comment"] = new_df["processed_comment"].astype(str).str.strip()
    new_df = new_df[new_df["processed_comment"] != ""].copy()

    return new_df



# Spark pipeline function section
# Spark -> preprocess(Pandas dataframe) -> write new collection -> export CSV with the same name

def run_comment_preprocess_pipeline(
    mongo_uri,
    source_db,
    source_collection,
    target_db,
    target_collection,
    season_col="season",
    comment_col="comment",
    min_tokens=2,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
):
    """
    Read comment data from MongoDB, then after text preprocessing:
    1. Write into a new collection
    2. Export a CSV with the same name
    """
    spark = connect_spark(mongo_uri)

    source_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=source_collection,
        query={},
        projection={"_id": 0}
    )

    if len(source_spark_df.head(1)) == 0:
        print("The source collection has no data")
        return pd.DataFrame()

    source_df = source_spark_df.toPandas()

    result_df = preprocess_comments_dataframe(
        df=source_df,
        season_col=season_col,
        comment_col=comment_col,
        min_tokens=min_tokens
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection,
        output_dir=output_dir
    )

    inserted_count = 0

    if not result_df.empty:
        result_spark_df = spark.createDataFrame(result_df)

        inserted_count = insert_dataframe_to_collection(
            df=result_spark_df,
            mongo_uri=mongo_uri,
            db_name=target_db,
            collection_name=target_collection,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=result_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No records after preprocessing")

    print(f"Source collection: {source_collection}")
    print(f"Number of source records: {len(source_df)}")
    print(f"Number of records after preprocessing: {len(result_df)}")
    print(f"New collection written successfully: {inserted_count} records")

    if not result_df.empty:
        print(f"CSV exported successfully: {output_csv_path}")

    return result_df

# Function invocation section

preprocessed_result = run_comment_preprocess_pipeline(
    mongo_uri=CLIENT,
    source_db=DEFAULT_DB,
    source_collection="dws_comment_model_filtered",
    target_db=DEFAULT_DB,
    target_collection="dws_comment_preprocessed",
    season_col="season",
    comment_col="comment",
    min_tokens=2,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
)

preprocessed_result.head()

Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.753 seconds.
DEBUG:jieba:Loading model cost 0.753 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.

Source collection: dws_comment_model_filtered
Number of source records: 2499
Number of records after preprocessing: 2285
New collection written successfully: 2285 records
CSV exported successfully: /content/dws_comment_preprocessed.csv

,season,comment,processed_comment
0,4,每天午休都看的咯咯直笑~,午休咯咯直笑
1,5,相比于Ross和Rachel的分分合合更喜欢看Chandler和Monica在一起的超甜蜜?...,相比RossRachel分分合合喜欢ChandlerMonica超甜蜜.健康恋爱关系.Joe...
2,5,从第五季开始喜欢乔伊,第五季喜欢乔伊
3,5,整整十季都很爱但是中期的编剧能力真的太强太强太强太强太强了，没有后期的狗血风主线，角色性格也...,整整十季爱中期编剧能力真的太强太强太强太强太强后期狗血风主线角色性格套路爱包袱抛出来对面最少...
4,5,看得停不下来，每次结尾都要这么有悬念吊人胃口吗，瞧瞧人家的编剧！,停不下来每次结尾悬念吊人胃口瞧瞧编剧

## Detailed analysis of the comments
Analyzes the sentiment of each comment by fusing multiple model

| Merging Scenario | Processing Method | Final Result |
|---|---|---|
| Both models have low confidence | If `star_top_score <= 0.35` and `tri_top_score <= 0.35` | Force the result to `neutral` |
| One model predicts positive while the other predicts negative | Invoke LLM-based review | The LLM directly determines the final label |
| The two models output different labels with a large confidence gap | If the labels are different and the score gap is ≥ `0.25`, invoke LLM-based review | The LLM directly determines the final label |
| Normal case | `final = 0.6 * star_dist + 0.4 * tri_dist` | Select the label with the highest final score |
| Unsupported polarity after weighted merging | If neither model supports `negative` but the merged result becomes `negative`, remove `negative` and renormalize; the same applies to `positive` | Prevent abnormal extreme sentiment outputs |
| Final negative review | Run an additional LLM review on comments finally labeled as `negative` | The negative label may be revised to `neutral` or `positive` |

In [26]:
# Sentiment analysis related functions
# Output collection: dws_comment_sentiment_analysis

def split_sentences_for_sentiment(text, max_chars=120):
    if pd.isna(text):
        return []

    text = str(text).strip()
    if not text:
        return []

    text = re.sub(r'[\t\r\n]+', ' ', text)
    parts = re.split(r'[。！？!?；;…]+|\.(?=\s|$)', text)
    parts = [p.strip() for p in parts if p.strip()]

    final_parts = []
    for part in parts:
        sub_parts = re.split(r'\s{2,}', part)
        for sub in sub_parts:
            sub = sub.strip()
            if not sub:
                continue

            if len(sub) <= max_chars:
                final_parts.append(sub)
            else:
                for i in range(0, len(sub), max_chars):
                    chunk = sub[i:i + max_chars].strip()
                    if chunk:
                        final_parts.append(chunk)

    return final_parts


def extract_one_keyword(text, kw_model):
    if pd.isna(text):
        return ""

    text = str(text).strip()
    if not text:
        return ""

    candidate_text = text

    try:
        keywords = kw_model.extract_keywords(
            text,
            keyphrase_ngram_range=(1, 2),
            top_n=3
        )
        for kw, score in keywords:
            kw = str(kw).strip()
            if kw:
                candidate_text = kw
                break
    except Exception as e:
        print("关键词模型提取失败:", e)
        print("文本内容:", text[:200])

    try:
        tokens = list(filter_stopwords(jieba.cut(candidate_text)))
    except Exception:
        tokens = list(jieba.cut(candidate_text))

    cleaned_tokens = []
    for w in tokens:
        w = str(w).strip()
        if not w:
            continue
        if " " in w:
            continue
        if len(w) < 2:
            continue
        if len(w) > 8:
            continue
        if re.fullmatch(r'[\W_]+', w):
            continue
        if re.fullmatch(r'\d+', w):
            continue
        cleaned_tokens.append(w)

    if cleaned_tokens:
        cleaned_text = "".join(cleaned_tokens)
        try:
            snow = SnowNLP(cleaned_text)
            kw_list = snow.keywords(3)
            for kw in kw_list:
                kw = str(kw).strip()
                if not kw:
                    continue
                if " " in kw:
                    continue
                if len(kw) < 2:
                    continue
                if len(kw) > 8:
                    continue
                if re.fullmatch(r'[\W_]+', kw):
                    continue
                if re.fullmatch(r'\d+', kw):
                    continue
                return kw
        except Exception:
            pass

    if cleaned_tokens:
        return cleaned_tokens[0]

    return ""


def star_label_to_number(label):
    match = re.search(r'(\d)', str(label))
    if match:
        return int(match.group(1))
    return None


def star_scores_to_sentiment_dist(score_items):
    dist = {"negative": 0.0, "neutral": 0.0, "positive": 0.0}

    for item in score_items:
        star = star_label_to_number(item["label"])
        score = item["score"]

        if star == 1:
            dist["negative"] += score
        elif star == 2:
            dist["negative"] += score * 0.7
            dist["neutral"] += score * 0.3
        elif star == 3:
            dist["neutral"] += score
        elif star == 4:
            dist["positive"] += score * 0.7
            dist["neutral"] += score * 0.3
        elif star == 5:
            dist["positive"] += score

    total = sum(dist.values())
    if total > 0:
        for k in dist:
            dist[k] /= total

    return dist


def normalize_cardiff_label(label):
    label = str(label).lower().strip()

    if label == "label_0":
        return "negative"
    if label == "label_1":
        return "neutral"
    if label == "label_2":
        return "positive"

    if "negative" in label:
        return "negative"
    if "neutral" in label:
        return "neutral"
    if "positive" in label:
        return "positive"

    return "neutral"


def three_class_scores_to_dist(score_items):
    dist = {"negative": 0.0, "neutral": 0.0, "positive": 0.0}

    for item in score_items:
        label = normalize_cardiff_label(item["label"])
        dist[label] += item["score"]

    total = sum(dist.values())
    if total > 0:
        for k in dist:
            dist[k] /= total

    return dist


def apply_domain_phrase_bias(comment, star_dist, tri_dist):
    text = str(comment).strip()

    pos_hit = any(re.search(p, text, flags=re.IGNORECASE) for p in positive_patterns)
    neg_hit = any(re.search(p, text, flags=re.IGNORECASE) for p in negative_patterns)

    star_dist = star_dist.copy()
    tri_dist = tri_dist.copy()

    if pos_hit and not neg_hit:
        star_dist["positive"] += 0.08
        tri_dist["positive"] += 0.08

    if neg_hit and not pos_hit:
        star_dist["negative"] += 0.08
        tri_dist["negative"] += 0.08

    for dist in [star_dist, tri_dist]:
        total = sum(dist.values())
        if total > 0:
            for k in dist:
                dist[k] /= total

    return star_dist, tri_dist


# Sentiment analysis with LLM functions

def build_llm_prompt(comment):
    return f"""
你是一个中文影视评论情绪分类助手。

请判断下面这条评论的整体情绪倾向，只能从这三个标签里选一个：
positive / neutral / negative

判断标准：
- positive：整体明确偏赞扬、推荐、喜欢、认可
- neutral：客观描述、中性表达、信息不足、褒贬不明显
- negative：整体明确偏批评、不满、否定、吐槽

注意：
1. 结合中文日常表达、影视评论语境、网络语气
2. 像“无理由五星”“看了N次不嫌多”“值得二刷”“越看越上头”通常偏 positive
3. 不要把轻微吐槽、普通评价、客观描述轻易判成 negative
4. 只返回 JSON，不要输出任何额外文字

输出格式：
{{"label":"positive","reason":"一句话理由"}}

评论：
{comment}
""".strip()


def call_llm_api(prompt):
    url = LLM_BASE_URL.rstrip("/") + LLM_CHAT_COMPLETIONS_PATH
    headers = {
        "Authorization": f"Bearer {LLM_API_TOKEN}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": LLM_MODEL_NAME,
        "messages": [
            {"role": "system", "content": "你是一个严谨的中文影视评论情绪分类助手。"},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0
    }

    last_error = None
    for attempt in range(LLM_MAX_RETRIES):
        try:
            resp = requests.post(url, headers=headers, json=payload, timeout=LLM_TIMEOUT)
            resp.raise_for_status()
            data = resp.json()
            return data["choices"][0]["message"]["content"]
        except Exception as e:
            last_error = e
            time.sleep(1.5 * (attempt + 1))

    raise RuntimeError(f"LLM Failed: {last_error}")


def parse_llm_output(raw_output):
    raw_output = str(raw_output).strip()

    try:
        obj = json.loads(raw_output)
        label = str(obj.get("label", "")).strip().lower()
        reason = str(obj.get("reason", "")).strip()

        if label not in ["positive", "neutral", "negative"]:
            return {
                "llm_label": "negative",
                "llm_reason": f"Label abnormality, defaulting to negative. Original:  {raw_output}",
                "llm_raw_output": raw_output
            }

        return {
            "llm_label": label,
            "llm_reason": reason,
            "llm_raw_output": raw_output
        }

    except Exception:
        match = re.search(r'"label"\s*:\s*"?(positive|neutral|negative)"?', raw_output, flags=re.IGNORECASE)
        if match:
            label = match.group(1).lower()
            return {
                "llm_label": label,
                "llm_reason": "Non-standard JSON, regex extraction successful",
                "llm_raw_output": raw_output
            }

        return {
            "llm_label": "negative",
            "llm_reason": "JSON parsing failed, defaulting to negative",
            "llm_raw_output": raw_output
        }


def review_single_negative_comment(comment):
    prompt = build_llm_prompt(comment)
    raw_output = call_llm_api(prompt)
    return parse_llm_output(raw_output)


def llm_judge_sentiment(comment):
    return review_single_negative_comment(comment)


# Sentiment decision functions

def get_top_label_and_score(dist):
    top_label = max(dist, key=dist.get)
    top_score = dist[top_label]
    return top_label, top_score


def renormalize_allowed_labels(dist, allowed_labels):
    filtered = {k: (dist[k] if k in allowed_labels else 0.0) for k in dist}
    total = sum(filtered.values())

    if total <= 0:
        n = len(allowed_labels)
        return {k: (1.0 / n if k in allowed_labels else 0.0) for k in dist}

    for k in filtered:
        filtered[k] /= total

    return filtered


def decide_final_sentiment(
    comment,
    star_dist,
    tri_dist,
    w_star=0.6,
    w_tri=0.4,
    low_conf_threshold=0.35,
    confidence_gap_threshold=0.25
):
    star_dist, tri_dist = apply_domain_phrase_bias(comment, star_dist, tri_dist)

    star_top_label, star_top_score = get_top_label_and_score(star_dist)
    tri_top_label, tri_top_score = get_top_label_and_score(tri_dist)

    if star_top_score <= low_conf_threshold and tri_top_score <= low_conf_threshold:
        merged = {"negative": 0.0, "neutral": 1.0, "positive": 0.0}
        return {
            "star_top_label": star_top_label,
            "star_top_score": star_top_score,
            "tri_top_label": tri_top_label,
            "tri_top_score": tri_top_score,
            "final_negative": merged["negative"],
            "final_neutral": merged["neutral"],
            "final_positive": merged["positive"],
            "sentiment_association": "neutral",
            "decision_type": "low_confidence_force_neutral"
        }

    if {star_top_label, tri_top_label} == {"positive", "negative"}:
        llm_result = llm_judge_sentiment(comment)
        llm_label = llm_result["llm_label"]

        merged = {"negative": 0.0, "neutral": 0.0, "positive": 0.0}
        merged[llm_label] = 1.0

        return {
            "star_top_label": star_top_label,
            "star_top_score": star_top_score,
            "tri_top_label": tri_top_label,
            "tri_top_score": tri_top_score,
            "final_negative": merged["negative"],
            "final_neutral": merged["neutral"],
            "final_positive": merged["positive"],
            "sentiment_association": llm_label,
            "decision_type": "llm_override_pos_neg_conflict"
        }

    if (
        star_top_label != tri_top_label
        and abs(star_top_score - tri_top_score) >= confidence_gap_threshold
    ):
        llm_result = llm_judge_sentiment(comment)
        llm_label = llm_result["llm_label"]

        merged = {"negative": 0.0, "neutral": 0.0, "positive": 0.0}
        merged[llm_label] = 1.0

        return {
            "star_top_label": star_top_label,
            "star_top_score": star_top_score,
            "tri_top_label": tri_top_label,
            "tri_top_score": tri_top_score,
            "final_negative": merged["negative"],
            "final_neutral": merged["neutral"],
            "final_positive": merged["positive"],
            "sentiment_association": llm_label,
            "decision_type": "llm_override_large_gap_conflict"
        }

    merged = {
        "negative": w_star * star_dist["negative"] + w_tri * tri_dist["negative"],
        "neutral":  w_star * star_dist["neutral"]  + w_tri * tri_dist["neutral"],
        "positive": w_star * star_dist["positive"] + w_tri * tri_dist["positive"],
    }
    final_label = max(merged, key=merged.get)
    decision_type = "weighted_merge"

    if star_top_label != "negative" and tri_top_label != "negative" and final_label == "negative":
        merged = renormalize_allowed_labels(merged, {"neutral", "positive"})
        final_label = max(merged, key=merged.get)
        decision_type += "_forbid_negative"

    if star_top_label != "positive" and tri_top_label != "positive" and final_label == "positive":
        merged = renormalize_allowed_labels(merged, {"negative", "neutral"})
        final_label = max(merged, key=merged.get)
        decision_type += "_forbid_positive"

    return {
        "star_top_label": star_top_label,
        "star_top_score": star_top_score,
        "tri_top_label": tri_top_label,
        "tri_top_score": tri_top_score,
        "final_negative": merged["negative"],
        "final_neutral": merged["neutral"],
        "final_positive": merged["positive"],
        "sentiment_association": final_label,
        "decision_type": decision_type
    }


def batch_analyze_sentiment(
    df,
    emotional_5_star,
    emotional_3_value,
    comment_col="comment",
    sentence_batch_size=64,
    max_chars=120,
    w_star=0.6,
    w_tri=0.4,
    low_conf_threshold=0.35,
    confidence_gap_threshold=0.25
):
    work_df = df[[comment_col]].copy().reset_index(drop=False).rename(columns={"index": "row_id"})
    sentence_rows = []

    for row in work_df.itertuples(index=False):
        row_id = row.row_id
        text = getattr(row, comment_col)

        sentences = split_sentences_for_sentiment(text, max_chars=max_chars)
        if not sentences:
            sentences = [str(text).strip()] if str(text).strip() else [""]

        total_len = sum(max(len(s), 1) for s in sentences)

        for sent in sentences:
            sentence_rows.append({
                "row_id": row_id,
                "sentence": sent,
                "sent_len": max(len(sent), 1),
                "total_len": max(total_len, 1)
            })

    sent_df = pd.DataFrame(sentence_rows)
    sentence_texts = sent_df["sentence"].tolist()

    star_outputs = emotional_5_star(
        sentence_texts,
        batch_size=sentence_batch_size,
        truncation=True,
        top_k=None
    )

    tri_outputs = emotional_3_value(
        sentence_texts,
        batch_size=sentence_batch_size,
        truncation=True,
        top_k=None
    )

    sent_df["star_dist"] = [star_scores_to_sentiment_dist(x) for x in star_outputs]
    sent_df["tri_dist"] = [three_class_scores_to_dist(x) for x in tri_outputs]
    sent_df["weight"] = sent_df["sent_len"] / sent_df["total_len"]

    result_rows = []

    for row_id, group in sent_df.groupby("row_id", sort=False):
        star_sum = {"negative": 0.0, "neutral": 0.0, "positive": 0.0}
        tri_sum = {"negative": 0.0, "neutral": 0.0, "positive": 0.0}

        for item in group.itertuples(index=False):
            w = item.weight
            for k in star_sum:
                star_sum[k] += item.star_dist[k] * w
                tri_sum[k] += item.tri_dist[k] * w

        comment_text = df.loc[row_id, comment_col]

        decision_result = decide_final_sentiment(
            comment=comment_text,
            star_dist=star_sum,
            tri_dist=tri_sum,
            w_star=w_star,
            w_tri=w_tri,
            low_conf_threshold=low_conf_threshold,
            confidence_gap_threshold=confidence_gap_threshold
        )

        result_rows.append({
            "row_id": row_id,

            "star_negative": star_sum["negative"],
            "star_neutral": star_sum["neutral"],
            "star_positive": star_sum["positive"],
            "star_top_label": decision_result["star_top_label"],
            "star_top_score": decision_result["star_top_score"],

            "tri_negative": tri_sum["negative"],
            "tri_neutral": tri_sum["neutral"],
            "tri_positive": tri_sum["positive"],
            "tri_top_label": decision_result["tri_top_label"],
            "tri_top_score": decision_result["tri_top_score"],

            "final_negative": decision_result["final_negative"],
            "final_neutral": decision_result["final_neutral"],
            "final_positive": decision_result["final_positive"],
            "sentiment_association": decision_result["sentiment_association"],
            "decision_type": decision_result["decision_type"]
        })

    return pd.DataFrame(result_rows)


def batch_llm_review_negatives(
    df,
    comment_col="comment",
    sentiment_col="sentiment_association",
    max_workers=None
):
    if max_workers is None:
        max_workers = LLM_THREAD_WORKERS

    new_df = df.copy()
    new_df["llm_label"] = ""
    new_df["llm_reason"] = ""
    new_df["llm_raw_output"] = ""
    new_df["final_label_after_llm"] = new_df[sentiment_col]

    target_indices = new_df[new_df[sentiment_col] == "negative"].index.tolist()

    if not target_indices:
        return new_df

    future_to_idx = {}

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        for idx in target_indices:
            comment = new_df.at[idx, comment_col]
            future = executor.submit(review_single_negative_comment, comment)
            future_to_idx[future] = idx

        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]

            try:
                result = future.result()
            except Exception as e:
                result = {
                    "llm_label": "negative",
                    "llm_reason": f"请求失败，默认保持 negative: {e}",
                    "llm_raw_output": ""
                }

            new_df.at[idx, "llm_label"] = result["llm_label"]
            new_df.at[idx, "llm_reason"] = result["llm_reason"]
            new_df.at[idx, "llm_raw_output"] = result["llm_raw_output"]

            if result["llm_label"] in ["neutral", "positive"]:
                new_df.at[idx, "final_label_after_llm"] = result["llm_label"]
            else:
                new_df.at[idx, "final_label_after_llm"] = "negative"

    return new_df


def print_sentiment_debug(row):
    print("Comment: ", row["comment"])
    print(
        "5_Star_Model ->",
        "negative:", round(row["star_negative"], 4),
        "neutral:", round(row["star_neutral"], 4),
        "positive:", round(row["star_positive"], 4),
        "| top:", row["star_top_label"],
        "| score:", round(row["star_top_score"], 4)
    )
    print(
        "3_Value_Model ->",
        "negative:", round(row["tri_negative"], 4),
        "neutral:", round(row["tri_neutral"], 4),
        "positive:", round(row["tri_positive"], 4),
        "| top:", row["tri_top_label"],
        "| score:", round(row["tri_top_score"], 4)
    )
    print(
        "Final_Result ->",
        "negative:", round(row["final_negative"], 4),
        "neutral:", round(row["final_neutral"], 4),
        "positive:", round(row["final_positive"], 4),
        "| final:", row["sentiment_association"],
        "| rule:", row["decision_type"]
    )
    print("Keyword: ", row["keyword"])
    print("-" * 80)


def analyze_comment_sentiment_dataframe(
    df,
    kw_model=None,
    emotional_5_star=None,
    emotional_3_value=None,
    season_col="season",
    comment_col="comment",
    sentence_batch_size=64,
    max_chars=120,
    w_star=0.6,
    w_tri=0.4,
    low_conf_threshold=0.35,
    confidence_gap_threshold=0.25,
    run_llm_review=True,
    verbose=False,
    print_n=20
):
    if kw_model is None:
        raise ValueError("kw_model was not provided")
    if emotional_5_star is None:
        raise ValueError("emotional_5_star was not provided")
    if emotional_3_value is None:
        raise ValueError("emotional_3_value was not provided")

    required_cols = [season_col, comment_col]
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing fields: {missing_cols}")

    work_df = df[[season_col, comment_col]].copy()
    work_df = work_df[work_df[comment_col].notna()].copy()
    work_df[comment_col] = work_df[comment_col].astype(str).str.strip()
    work_df = work_df[work_df[comment_col] != ""].copy()
    work_df = work_df.reset_index(drop=True)

    work_df["keyword"] = work_df[comment_col].apply(lambda x: extract_one_keyword(x, kw_model))

    sentiment_df = batch_analyze_sentiment(
        df=work_df,
        emotional_5_star=emotional_5_star,
        emotional_3_value=emotional_3_value,
        comment_col=comment_col,
        sentence_batch_size=sentence_batch_size,
        max_chars=max_chars,
        w_star=w_star,
        w_tri=w_tri,
        low_conf_threshold=low_conf_threshold,
        confidence_gap_threshold=confidence_gap_threshold
    )

    result_df = work_df.reset_index(drop=False).rename(columns={"index": "row_id"})
    result_df = result_df.merge(sentiment_df, on="row_id", how="left")

    if run_llm_review:
        result_df = batch_llm_review_negatives(
            df=result_df,
            comment_col=comment_col,
            sentiment_col="sentiment_association",
            max_workers=LLM_THREAD_WORKERS
        )
    else:
        result_df["llm_label"] = ""
        result_df["llm_reason"] = ""
        result_df["llm_raw_output"] = ""
        result_df["final_label_after_llm"] = result_df["sentiment_association"]

    final_cols = [
        season_col,
        comment_col,
        "keyword",

        "star_negative", "star_neutral", "star_positive", "star_top_label", "star_top_score",
        "tri_negative", "tri_neutral", "tri_positive", "tri_top_label", "tri_top_score",

        "final_negative", "final_neutral", "final_positive",
        "sentiment_association",
        "decision_type",

        "llm_label",
        "llm_reason",
        "final_label_after_llm"
    ]

    result_df = result_df[final_cols]

    if verbose:
        for _, row in result_df.head(print_n).iterrows():
            print_sentiment_debug(row)

    return result_df


def run_comment_sentiment_pipeline(
    mongo_uri_or_spark,
    source_db,
    source_collection,
    target_db,
    target_collection,
    kw_model=None,
    emotional_5_star=None,
    emotional_3_value=None,
    season_col="season",
    comment_col="comment",
    sentence_batch_size=64,
    max_chars=120,
    w_star=0.6,
    w_tri=0.4,
    low_conf_threshold=0.35,
    confidence_gap_threshold=0.25,
    run_llm_review=True,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True,
    verbose=False,
    print_n=20
):
    spark = ensure_spark_session(mongo_uri_or_spark)
    mongo_uri = spark.conf.get("spark.mongodb.read.connection.uri")

    source_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=source_collection,
        query={},
        projection={"_id": 0}
    )

    if len(source_spark_df.head(1)) == 0:
        print("The source collection has no data")
        return pd.DataFrame()

    source_df = source_spark_df.toPandas()

    result_df = analyze_comment_sentiment_dataframe(
        df=source_df,
        kw_model=kw_model,
        emotional_5_star=emotional_5_star,
        emotional_3_value=emotional_3_value,
        season_col=season_col,
        comment_col=comment_col,
        sentence_batch_size=sentence_batch_size,
        max_chars=max_chars,
        w_star=w_star,
        w_tri=w_tri,
        low_conf_threshold=low_conf_threshold,
        confidence_gap_threshold=confidence_gap_threshold,
        run_llm_review=run_llm_review,
        verbose=verbose,
        print_n=print_n
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection,
        output_dir=output_dir
    )

    inserted_count = 0

    if not result_df.empty:
        result_spark_df = spark.createDataFrame(result_df)

        inserted_count = insert_dataframe_to_collection(
            df=result_spark_df,
            mongo_uri=mongo_uri,
            db_name=target_db,
            collection_name=target_collection,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=result_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No sentiment records generated")

    print(f"Source collection: {source_collection}")
    print(f"Number of source records: {len(source_df)}")
    print(f"Number of sentiment records: {len(result_df)}")
    print(f"Sentiment collection written successfully: {inserted_count} records")

    if not result_df.empty:
        print(f"Sentiment CSV exported successfully: {output_csv_path}")

    return result_df

sentiment_df = run_comment_sentiment_pipeline(
    mongo_uri_or_spark=CLIENT,
    source_db=DEFAULT_DB,
    source_collection="dws_comment_preprocessed",
    target_db=DEFAULT_DB,
    target_collection="dws_comment_sentiment_analysis",

    kw_model=kw_model,
    emotional_5_star=emotional_5_star,
    emotional_3_value=emotional_3_value,

    sentence_batch_size=64,
    max_chars=120,

    w_star=0.6,
    w_tri=0.4,
    low_conf_threshold=0.35,
    confidence_gap_threshold=0.25,

    run_llm_review=True,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True,
    verbose=True,
    print_n=20
)

print(sentiment_df.head())

Comment:  就剩一季了。强迫症。
5_Star_Model -> negative: 0.4625 neutral: 0.3376 positive: 0.1999 | top: negative | score: 0.4625
3_Value_Model -> negative: 0.4296 neutral: 0.3706 positive: 0.1998 | top: negative | score: 0.4296
Final_Result -> negative: 0.4493 neutral: 0.3508 positive: 0.1998 | final: negative | rule: weighted_merge
Keyword:  强迫症
--------------------------------------------------------------------------------
Comment:  看的真快。乔伊被设定的越来越简单，钱德勒婚后不好玩了。依然喜欢ross，越发觉得莫妮卡不错。
5_Star_Model -> negative: 0.3255 neutral: 0.4805 positive: 0.194 | top: neutral | score: 0.4449
3_Value_Model -> negative: 0.3699 neutral: 0.2515 positive: 0.3786 | top: positive | score: 0.4246
Final_Result -> negative: 0.3178 neutral: 0.3601 positive: 0.3221 | final: neutral | rule: weighted_merge
Keyword:  简单
--------------------------------------------------------------------------------
Comment:  有点拖拉的一季，钱德勒和莫妮卡检查的时候我觉得好可怜，特别是结果出来的时候！一直认为麦克就是菲比的归属了！哪怕最终结局会安排罗斯和瑞秋在一起，我也希望乔伊曾经拥有过！一直不喜欢黑人！爱情公寓，你还要抄多少季？
5_Star_Model -> negative: 0.2044 neutral: 0.3889 positive: 0.4066 | top: positive | score: 0.4066
3_Value_Model -> negative: 0.5849 neutral: 0.2568 positive: 0.1582 | top: negative | score: 0.5849
Final_Result -> negative: 1.0 neutral: 0.0 positive: 0.0 | final: negative | rule: llm_override_pos_neg_conflict
Keyword:  罗斯
--------------------------------------------------------------------------------
Comment:  真的只剩下一季了...
5_Star_Model -> negative: 0.428 neutral: 0.3282 positive: 0.2437 | top: negative | score: 0.428
3_Value_Model -> negative: 0.5593 neutral: 0.3346 positive: 0.1061 | top: negative | score: 0.5593
Final_Result -> negative: 0.4805 neutral: 0.3308 positive: 0.1887 | final: negative | rule: weighted_merge
Keyword:  剩下
--------------------------------------------------------------------------------
Comment:  好喜欢RJ在一起~~让RR随风飘逝吧~~
5_Star_Model -> negative: 0.0279 neutral: 0.1902 positive: 0.7819 | top: positive | score: 0.7819
3_Value_Model -> negative: 0.0838 neutral: 0.2354 positive: 0.6808 | top: positive | score: 0.6808
Final_Result -> negative: 0.0503 neutral: 0.2083 positive: 0.7414 | final: positive | rule: weighted_merge
Keyword:  rjrr
--------------------------------------------------------------------------------
Comment:  罗斯和瑞秋是该剧设定的主角，其恋情也是整个系列的线索，但这两个人的性格和爱情故事却极其让人厌恶。另外，疯疯癫癫的菲比也很讨厌。
5_Star_Model -> negative: 0.3544 neutral: 0.4941 positive: 0.1515 | top: neutral | score: 0.4941
3_Value_Model -> negative: 0.7692 neutral: 0.1632 positive: 0.0675 | top: negative | score: 0.7692
Final_Result -> negative: 1.0 neutral: 0.0 positive: 0.0 | final: negative | rule: llm_override_large_gap_conflict
Keyword:  设定
--------------------------------------------------------------------------------
Comment:  舍不得看完啊
5_Star_Model -> negative: 0.6012 neutral: 0.3166 positive: 0.0822 | top: negative | score: 0.6012
3_Value_Model -> negative: 0.6702 neutral: 0.1886 positive: 0.1412 | top: negative | score: 0.6702
Final_Result -> negative: 0.6288 neutral: 0.2654 positive: 0.1058 | final: negative | rule: weighted_merge
Keyword:  舍不得
--------------------------------------------------------------------------------
Comment:  三角什么的不喜欢
5_Star_Model -> negative: 0.3808 neutral: 0.5034 positive: 0.1158 | top: neutral | score: 0.5034
3_Value_Model -> negative: 0.6866 neutral: 0.219 positive: 0.0944 | top: negative | score: 0.6866
Final_Result -> negative: 0.5031 neutral: 0.3896 positive: 0.1073 | final: negative | rule: weighted_merge
Keyword:  喜欢
--------------------------------------------------------------------------------
Comment:  大家喜欢浪子是因为总以为浪子会回头，在非现实世界里这种烂俗梗早被玩儿坏了。但是看到第九季，看到joey这个游戏人间的玩咖忽然间也触碰到了真爱，还是难免被打动。就暂缓揣摩剧作法，泡杯咖啡，开开心心迎接十年老朋友们的结局吧
5_Star_Model -> negative: 0.2607 neutral: 0.3873 positive: 0.3521 | top: neutral | score: 0.3873
3_Value_Model -> negative: 0.4274 neutral: 0.2859 positive: 0.2867 | top: negative | score: 0.4274
Final_Result -> negative: 0.3274 neutral: 0.3467 positive: 0.3259 | final: neutral | rule: weighted_merge
Keyword:  回头
--------------------------------------------------------------------------------
Comment:  joey和rachel的组合真的有点扯啊
5_Star_Model -> negative: 0.3854 neutral: 0.3202 positive: 0.2944 | top: negative | score: 0.3854
3_Value_Model -> negative: 0.6754 neutral: 0.2303 positive: 0.0943 | top: negative | score: 0.6754
Final_Result -> negative: 0.5014 neutral: 0.2843 positive: 0.2144 | final: negative | rule: weighted_merge
Keyword:  组合
--------------------------------------------------------------------------------
Comment:  实在不能接受RACHAL和JOEY暧昧来暧昧去的。。。三观碎一地。
5_Star_Model -> negative: 0.6839 neutral: 0.2543 positive: 0.0617 | top: negative | score: 0.6839
3_Value_Model -> negative: 0.7674 neutral: 0.1648 positive: 0.0678 | top: negative | score: 0.7674
Final_Result -> negative: 0.7173 neutral: 0.2185 positive: 0.0641 | final: negative | rule: weighted_merge
Keyword:  暧昧
--------------------------------------------------------------------------------
Comment:  明星越来越多……老公都来助阵了
5_Star_Model -> negative: 0.0746 neutral: 0.22 positive: 0.7054 | top: positive | score: 0.7054
3_Value_Model -> negative: 0.263 neutral: 0.4387 positive: 0.2982 | top: neutral | score: 0.4387
Final_Result -> negative: 0.0 neutral: 1.0 positive: 0.0 | final: neutral | rule: llm_override_large_gap_conflict
Keyword:  助阵
--------------------------------------------------------------------------------
Comment:  经典至极，看过无数遍
5_Star_Model -> negative: 0.0357 neutral: 0.2668 positive: 0.6976 | top: positive | score: 0.6976
3_Value_Model -> negative: 0.0748 neutral: 0.1205 positive: 0.8047 | top: positive | score: 0.8047
Final_Result -> negative: 0.0513 neutral: 0.2082 positive: 0.7404 | final: positive | rule: weighted_merge
Keyword:  无数
--------------------------------------------------------------------------------
Comment:  最后一集的重新组合真有些混乱，但我觉得这样倒是很好。
5_Star_Model -> negative: 0.1984 neutral: 0.5306 positive: 0.271 | top: neutral | score: 0.5306
3_Value_Model -> negative: 0.3836 neutral: 0.2777 positive: 0.3388 | top: negative | score: 0.3836
Final_Result -> negative: 0.2725 neutral: 0.4294 positive: 0.2981 | final: neutral | rule: weighted_merge
Keyword:  组合
--------------------------------------------------------------------------------
Comment:  怎么会有这么好看的东西啊：）
5_Star_Model -> negative: 0.2768 neutral: 0.257 positive: 0.4662 | top: positive | score: 0.4662
3_Value_Model -> negative: 0.2502 neutral: 0.2167 positive: 0.533 | top: positive | score: 0.533
Final_Result -> negative: 0.2662 neutral: 0.2409 positive: 0.4929 | final: positive | rule: weighted_merge
Keyword:  东西
--------------------------------------------------------------------------------
Comment:  突然就追到了这里，竟然已九季！为什么是J&R两个在一起了？？？
5_Star_Model -> negative: 0.2422 neutral: 0.3132 positive: 0.4447 | top: positive | score: 0.4447
3_Value_Model -> negative: 0.3455 neutral: 0.3884 positive: 0.2661 | top: neutral | score: 0.3884
Final_Result -> negative: 0.2835 neutral: 0.3433 positive: 0.3732 | final: positive | rule: weighted_merge
Keyword:  已九季
--------------------------------------------------------------------------------
Comment:  第5集菲比的庆生会，17集老友记也开始上网了，瑞秋和Joey互表心意了。第九季了啊好快，真不想结束愉快的旅程但是又很期待。
5_Star_Model -> negative: 0.0614 neutral: 0.3348 positive: 0.6038 | top: positive | score: 0.6038
3_Value_Model -> negative: 0.152 neutral: 0.3634 positive: 0.4846 | top: positive | score: 0.4846
Final_Result -> negative: 0.0976 neutral: 0.3462 positive: 0.5561 | final: positive | rule: weighted_merge
Keyword:  庆生
--------------------------------------------------------------------------------
Comment:  这两季的Joey简直是小天使般存在，从他得知Phoebe or Rachel pregnant愿意主动承担责任共同面对，到大家为彩票痴狂疯狂许愿，而他许下了Chandler面试通过的愿望，有这样的朋友人生是多么幸运
5_Star_Model -> negative: 0.1894 neutral: 0.4149 positive: 0.3957 | top: neutral | score: 0.4149
3_Value_Model -> negative: 0.0756 neutral: 0.1352 positive: 0.7892 | top: positive | score: 0.7892
Final_Result -> negative: 0.0 neutral: 0.0 positive: 1.0 | final: positive | rule: llm_override_large_gap_conflict
Keyword:  小天使
--------------------------------------------------------------------------------
Comment:  oh my god！第九季了！一群可爱的人啊！
5_Star_Model -> negative: 0.1107 neutral: 0.2038 positive: 0.6855 | top: positive | score: 0.6855
3_Value_Model -> negative: 0.2174 neutral: 0.2579 positive: 0.5247 | top: positive | score: 0.5247
Final_Result -> negative: 0.1534 neutral: 0.2254 positive: 0.6212 | final: positive | rule: weighted_merge
Keyword:  可爱
--------------------------------------------------------------------------------
Comment:  钱德勒对爱与婚姻的看法常常打动我，回顾集里莫妮卡问他婚后的生活样式，他的回答让我初次看到，婚后不是打开一个截然不同的新生活，而是此前生活更美好的延续，不仅是夫妻小孩，还留给Joey一个车库养老，它不走向狭窄，反而是更温暖的团聚。
5_Star_Model -> negative: 0.0919 neutral: 0.4166 positive: 0.4915 | top: positive | score: 0.4915
3_Value_Model -> negative: 0.2307 neutral: 0.326 positive: 0.4433 | top: positive | score: 0.4433
Final_Result -> negative: 0.1474 neutral: 0.3804 positive: 0.4722 | final: positive | rule: weighted_merge
Keyword:  回顾
--------------------------------------------------------------------------------
Source collection: dws_comment_preprocessed
Number of source records: 2285
Number of sentiment records: 2285
Sentiment collection written successfully: 2285 records
Sentiment CSV exported successfully: /content/dws_comment_sentiment_analysis.csv
   season                                            comment keyword  \
0       9                                         就剩一季了。强迫症。     强迫症
1       9     看的真快。乔伊被设定的越来越简单，钱德勒婚后不好玩了。依然喜欢ross，越发觉得莫妮卡不错。      简单
2       9  有点拖拉的一季，钱德勒和莫妮卡检查的时候我觉得好可怜，特别是结果出来的时候！一直认为麦克就是...      罗斯
3       9                                        真的只剩下一季了...      剩下
4       9                               好喜欢RJ在一起~~让RR随风飘逝吧~~    rjrr

   star_negative  star_neutral  star_positive star_top_label  star_top_score  \
0       0.462451      0.337643       0.199907       negative        0.462451
1       0.325473      0.480498       0.194029        neutral        0.444906
2       0.204436      0.388928       0.406636       positive        0.406636
3       0.428043      0.328210       0.243747       negative        0.428043
4       0.027889      0.190245       0.781866       positive        0.781866

   tri_negative  tri_neutral  ...  tri_top_label tri_top_score  \
0      0.429604     0.370642  ...       negative      0.429604
1      0.369912     0.251486  ...       positive      0.424632
2      0.584943     0.256847  ...       negative      0.584943
3      0.559296     0.334560  ...       negative      0.559296
4      0.083813     0.235418  ...       positive      0.680768

   final_negative  final_neutral  final_positive  sentiment_association  \
0        0.449312       0.350842        0.199846               negative
1        0.317823       0.360086        0.322091                neutral
2        1.000000       0.000000        0.000000               negative
3        0.480545       0.330750        0.188705               negative
4        0.050259       0.208315        0.741427               positive

                   decision_type llm_label                       llm_reason  \
0                 weighted_merge   neutral          评论仅陈述事实和轻微个人感受，无明显褒贬倾向。
1                 weighted_merge
2  llm_override_pos_neg_conflict  negative  评论明确表达了对剧情拖拉、角色命运的不满，并直接批评了抄袭行为
3                 weighted_merge  negative    评论表达了明显的遗憾和失落情绪，暗示对剧集即将完结的不满。
4                 weighted_merge

  final_label_after_llm
0               neutral
1               neutral
2              negative
3              negative
4              positive

[5 rows x 21 columns]

## Pool testing
Evaluate and screen topic classification models through smoke testing and concurrent pressure testing

| Merging Scenario | Processing Method | Final Result |
|---|---|---|
| The model passes the smoke test | Set `available = result["success"]` | The model is added to the preliminary available model list `prelim_available_configs` |
| The model fails the smoke test | Set `available = False` | The model is eliminated immediately and will not proceed to the pressure testing stage |
| The model meets the pressure test success-rate threshold | If `success_rate >= min_success_rate` (default: `0.8`) | The model is added to the final available model pool `final_available_model_configs` |
| The model does not meet the pressure test success-rate threshold | If `success_rate < min_success_rate` | The model is excluded from the production-ready model list |
| All models fail the evaluation | If `AVAILABLE_TOPIC_MODELS` is empty | A runtime error is raised to stop the subsequent pipeline execution |

In [29]:
# Test topic model pool
# Purpose:
# Test the pool of topic classification models to identify which ones are stable and performant enough for production use.
# Steps:
# 1. For each model, do a basic smoke test with a fixed comment to check
# 2. For models that pass the smoke test, run a concurrent pressure test with multiple threads and multiple rounds
# 3. Evaluate the success rate and average response time under pressure for each model
# 4. Only models that achieve a success rate above the threshold (e.g., 80%) will be added to the AVAILABLE_TOPIC_MODELS list for production use.
# Output: A report of the test results for each model, and an updated list of available models that passed the tests.


def test_single_topic_model_once(model_cfg, candidate_labels=None, test_comment="这部剧剧情紧凑，演员演技也很好"):
    """
    Single test of one topic model with one comment,
    return success status, elapsed time, and parsed topic category if successful.
    """
    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    start_time = time.time()

    try:
        prompt = build_topic_llm_prompt(test_comment, candidate_labels=candidate_labels)
        raw_output = call_single_topic_llm_api(prompt, model_cfg)
        parsed = parse_topic_llm_output(raw_output, candidate_labels=candidate_labels)
        elapsed = time.time() - start_time

        return {
            "success": True,
            "elapsed": elapsed,
            "topic_category": parsed.get("topic_category", "其他"),
            "reason": parsed.get("llm_topic_reason", ""),
            "raw_output": raw_output,
            "error": ""
        }

    except Exception as e:
        elapsed = time.time() - start_time
        return {
            "success": False,
            "elapsed": elapsed,
            "topic_category": "",
            "reason": "",
            "raw_output": "",
            "error": str(e)
        }


def smoke_test_topic_model(model_cfg, candidate_labels=None, test_comment="这部剧剧情紧凑，演员演技也很好"):
    """
    Basic smoke test for a single topic model configuration.
    """
    result = test_single_topic_model_once(
        model_cfg=model_cfg,
        candidate_labels=candidate_labels,
        test_comment=test_comment
    )

    return {
        "model_name": model_cfg["name"],
        "available": result["success"],
        "elapsed": result["elapsed"],
        "topic_category": result.get("topic_category", ""),
        "reason": result.get("reason", ""),
        "raw_output": result.get("raw_output", ""),
        "error": result.get("error", "")
    }


def concurrent_pressure_test_topic_model(
    model_cfg,
    candidate_labels=None,
    test_comments=None,
    rounds_per_worker=2
):
    """
    Concurrent pressure test for a single topic model configuration,
    simulating multiple threads and multiple rounds of requests.
    """

    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    if test_comments is None:
        test_comments = [
            "这部剧剧情紧凑，人物塑造不错，演员演技在线",
            "这部作品节奏太慢了，但是画面和配乐不错",
            "主角演技很好，不过剧情后半段有点拖沓",
            "这部片子的主题表达很清晰，情感也很到位",
            "特效做得不错，但故事整体比较普通",
        ]

    worker_count = model_cfg["thread_workers"]
    total_tasks = worker_count * rounds_per_worker

    futures = []
    results = []

    start_all = time.time()

    with ThreadPoolExecutor(max_workers=worker_count) as executor:
        for i in range(total_tasks):
            comment = test_comments[i % len(test_comments)]
            futures.append(
                executor.submit(
                    test_single_topic_model_once,
                    model_cfg,
                    candidate_labels,
                    comment
                )
            )

        for future in as_completed(futures):
            results.append(future.result())

    total_elapsed = time.time() - start_all

    success_count = sum(1 for r in results if r["success"])
    fail_count = total_tasks - success_count
    success_rate = success_count / total_tasks if total_tasks > 0 else 0.0

    success_elapsed_list = [r["elapsed"] for r in results if r["success"]]
    avg_success_elapsed = (
        sum(success_elapsed_list) / len(success_elapsed_list)
        if success_elapsed_list else None
    )

    sample_errors = [r["error"] for r in results if not r["success"]][:3]

    return {
        "model_name": model_cfg["name"],
        "thread_workers": worker_count,
        "rounds_per_worker": rounds_per_worker,
        "total_requests": total_tasks,
        "success_count": success_count,
        "fail_count": fail_count,
        "success_rate": success_rate,
        "avg_success_elapsed": avg_success_elapsed,
        "total_elapsed": total_elapsed,
        "sample_errors": sample_errors
    }


def test_topic_model_pool(
    model_configs=None,
    candidate_labels=None,
    smoke_test_comment="这部剧剧情紧凑，人物塑造不错，演员演技在线",
    pressure_test_comments=None,
    rounds_per_worker=2,
    min_success_rate=0.8
):
    """
    Test the pool of topic classification models in two stages:
    1. Basic smoke test for each model configuration to check
       if it can return a valid topic category for a fixed comment.
    2. For models that pass the smoke test, run a concurrent pressure test with multiple
       threads and multiple rounds of requests, and evaluate the success rate and average response time.
    Only models that achieve a success rate above the specified threshold will be considered
    available for production use and added to the final list of available models.
    """

    if model_configs is None:
        model_configs = TOPIC_MODEL_CONFIGS
    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    print("=" * 80)
    print("Stage A: Basic Smoke Test for Topic Models")
    print("=" * 80)

    smoke_results = []
    prelim_available_configs = []

    with ThreadPoolExecutor(max_workers=len(model_configs)) as executor:
        future_to_model = {
            executor.submit(
                smoke_test_topic_model,
                model_cfg,
                candidate_labels,
                smoke_test_comment
            ): model_cfg["name"]
            for model_cfg in model_configs
        }

        for future in as_completed(future_to_model):
            result = future.result()
            smoke_results.append(result)

    for result in smoke_results:
        if result["available"]:
            print(f"[OK] Model: {result['model_name']}")
            print(f"     Single Request Time: {result['elapsed']:.2f}s")
            print(f"     Returned Topic: {result['topic_category']}")
            print(f"     Return Reason: {result['reason']}")
            print("-" * 80)

            matched_cfg = next(
                (cfg for cfg in model_configs if cfg["name"] == result["model_name"]),
                None
            )
            if matched_cfg is not None:
                prelim_available_configs.append(matched_cfg)
        else:
            print(f"[FAIL] Model: {result['model_name']}")
            print(f"       Error Message: {result['error']}")
            print("-" * 80)

    print(f"Basic Smoke Test - Total Models: {len(model_configs)}")
    print(f"Basic Smoke Test - Passed Models: {len(prelim_available_configs)}")
    print("=" * 80)

    if not prelim_available_configs:
        return [], {
            "smoke_results": smoke_results,
            "pressure_results": []
        }

    print("=" * 80)
    print("Stage B: Concurrent Pressure Test for Topic Models")
    print("=" * 80)

    pressure_results = []
    final_available_model_configs = []

    for model_cfg in prelim_available_configs:
        result = concurrent_pressure_test_topic_model(
            model_cfg=model_cfg,
            candidate_labels=candidate_labels,
            test_comments=pressure_test_comments,
            rounds_per_worker=rounds_per_worker
        )
        pressure_results.append(result)

        print(f"Model: {result['model_name']}")
        print(f"  Configured Thread Count: {result['thread_workers']}")
        print(f"  Test Rounds per Thread: {result['rounds_per_worker']}")
        print(f"  Total Requests: {result['total_requests']}")
        print(f"  Success Count: {result['success_count']}")
        print(f"  Failure Count: {result['fail_count']}")
        print(f"  Success Rate: {result['success_rate']:.2%}")
        print(
            f"  Average Success Time: "
            f"{result['avg_success_elapsed']:.2f}s"
            if result['avg_success_elapsed'] is not None else
            "  Average Success Time: None"
        )
        print(f"  Total Test Time: {result['total_elapsed']:.2f}s")

        if result["sample_errors"]:
            print(f"  Sample Errors: {result['sample_errors']}")

        if result["success_rate"] >= min_success_rate:
            matched_cfg = next(
                (cfg for cfg in prelim_available_configs if cfg["name"] == result["model_name"]),
                None
            )
            if matched_cfg is not None:
                final_available_model_configs.append(matched_cfg)
            print("  Status: Passed")
        else:
            print("  Status: Failed")

        print("-" * 80)

    print(f"Final Available Models: {len(final_available_model_configs)} / {len(model_configs)}")
    print("=" * 80)

    return final_available_model_configs, {
        "smoke_results": smoke_results,
        "pressure_results": pressure_results
    }


AVAILABLE_TOPIC_MODELS, TOPIC_MODEL_TEST_RESULTS = test_topic_model_pool(
    model_configs=TOPIC_MODEL_CONFIGS,
    candidate_labels=DEFAULT_CANDIDATE_LABELS,
    smoke_test_comment="这部剧剧情紧凑，人物塑造不错，演员演技在线",
    pressure_test_comments=[
        "这部剧剧情紧凑，人物塑造不错，演员演技在线",
        "节奏有点慢，但是摄影和配乐很好",
        "演员表现很自然，就是后面剧情有点弱",
        "主题表达很完整，看完很有感触",
        "特效不错，不过故事比较普通"
    ],
    rounds_per_worker=2,
    min_success_rate=0.8
)

if not AVAILABLE_TOPIC_MODELS:
    raise RuntimeError("NO TOPIC MODEL AVAILABLE AFTER TESTING.CHECK THE TEST RESULTS FOR DETAILS.")

================================================================================
Stage A: Basic Smoke Test for Topic Models
================================================================================
[OK] Model: alibaba/qwen-turbo
     Single Request Time: 1.68s
     Returned Topic: 剧情
     Return Reason: 评论主要提到剧情紧凑和人物塑造，属于对剧情的评价。
--------------------------------------------------------------------------------
[OK] Model: alibaba/kimi-k2.5
     Single Request Time: 1.89s
     Returned Topic: 剧情
     Return Reason: 评论核心评价对象是剧情紧凑和人物塑造，演员演技仅作为补充提及
--------------------------------------------------------------------------------
[OK] Model: deepseek/deepseek-chat
     Single Request Time: 1.93s
     Returned Topic: 剧情
     Return Reason: 评论的核心是赞扬剧情紧凑和人物塑造，演员演技是次要补充
--------------------------------------------------------------------------------
[OK] Model: alibaba/deepseek-v3.1
     Single Request Time: 1.96s
     Returned Topic: 剧情
     Return Reason: 评论重点强调了剧情紧凑这一核心要素
--------------------------------------------------------------------------------
[OK] Model: alibaba/qwen-turbo-latest
     Single Request Time: 2.04s
     Returned Topic: 剧情
     Return Reason: 评论中明确提到“剧情紧凑”，是主要评价点
--------------------------------------------------------------------------------
[OK] Model: moonshot/kimi-k2-turbo-preview
     Single Request Time: 2.11s
     Returned Topic: 剧情
     Return Reason: 评论首先强调“剧情紧凑”，随后才提及人物与演技，核心关注点落在剧情本身。
--------------------------------------------------------------------------------
[OK] Model: alibaba/MiniMax-M2.5
     Single Request Time: 2.58s
     Returned Topic: 剧情
     Return Reason: 评论重点评价了剧情紧凑和人物塑造，对演员的提及相对次要
--------------------------------------------------------------------------------
[OK] Model: alibaba/deepseek-v3.2-exp
     Single Request Time: 2.93s
     Returned Topic: 剧情
     Return Reason: 评论重点强调了剧情紧凑和人物塑造
--------------------------------------------------------------------------------
Basic Smoke Test - Total Models: 8
Basic Smoke Test - Passed Models: 8
================================================================================
================================================================================
Stage B: Concurrent Pressure Test for Topic Models
================================================================================
Model: alibaba/qwen-turbo
  Configured Thread Count: 8
  Test Rounds per Thread: 2
  Total Requests: 16
  Success Count: 16
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 1.70s
  Total Test Time: 4.19s
  Status: Passed
--------------------------------------------------------------------------------
Model: alibaba/kimi-k2.5
  Configured Thread Count: 8
  Test Rounds per Thread: 2
  Total Requests: 16
  Success Count: 16
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 3.74s
  Total Test Time: 8.96s
  Status: Passed
--------------------------------------------------------------------------------
Model: deepseek/deepseek-chat
  Configured Thread Count: 20
  Test Rounds per Thread: 2
  Total Requests: 40
  Success Count: 40
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 8.28s
  Total Test Time: 17.86s
  Status: Passed
--------------------------------------------------------------------------------
Model: alibaba/deepseek-v3.1
  Configured Thread Count: 8
  Test Rounds per Thread: 2
  Total Requests: 16
  Success Count: 16
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 2.11s
  Total Test Time: 5.29s
  Status: Passed
--------------------------------------------------------------------------------
Model: alibaba/qwen-turbo-latest
  Configured Thread Count: 8
  Test Rounds per Thread: 2
  Total Requests: 16
  Success Count: 16
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 1.77s
  Total Test Time: 4.58s
  Status: Passed
--------------------------------------------------------------------------------
Model: moonshot/kimi-k2-turbo-preview
  Configured Thread Count: 3
  Test Rounds per Thread: 2
  Total Requests: 6
  Success Count: 6
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 2.15s
  Total Test Time: 5.93s
  Status: Passed
--------------------------------------------------------------------------------
Model: alibaba/MiniMax-M2.5
  Configured Thread Count: 8
  Test Rounds per Thread: 2
  Total Requests: 16
  Success Count: 16
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 4.48s
  Total Test Time: 11.32s
  Status: Passed
--------------------------------------------------------------------------------
Model: alibaba/deepseek-v3.2-exp
  Configured Thread Count: 10
  Test Rounds per Thread: 2
  Total Requests: 20
  Success Count: 20
  Failure Count: 0
  Success Rate: 100.00%
  Average Success Time: 2.32s
  Total Test Time: 6.48s
  Status: Passed
--------------------------------------------------------------------------------
Final Available Models: 8 / 8
================================================================================

## LLM Classify
Perform topic classification on comment data through a multi-model concurrent architecture

| Focus Area | Implementation Details | Purpose |
|---|---|---|
| Concurrency structure | Each model uses a `TopicModelWorker` with its own `ThreadPoolExecutor` | Supports model-level and thread-level concurrency |
| Task dispatching | Each worker uses `queue.Queue()`, and tasks are assigned by `idx % len(model_workers)` | Ensures thread-safe and balanced task distribution |
| Worker execution | Threads continuously run `worker_loop()` to fetch and process tasks | Enables continuous parallel processing |
| Model priority and failover | `failover_models = [self.model_cfg] + other_models` | Tries the assigned model first and falls back to others if needed |
| Retry handling | Each request uses `max_retries` with `time.sleep(1.5 * (attempt + 1))` | Improves robustness against temporary failures |
| Full-failure fallback | If all models fail, return `Other` with an error message | Prevents single-task failure from interrupting the pipeline |
| Result synchronization | Use `with self.lock:` and `task_queue.join()` | Prevents write conflicts and ensures all tasks finish before aggregation |
| Safe shutdown and parsing tolerance | Use stop signals, `None`, and `executor.shutdown(wait=True)`; fallback to regex if JSON parsing fails | Ensures safe worker termination and more robust output parsing |

In [30]:
# Topic only - Multi-model concurrent version
# Output collection: dws_comment_topic_analysis


# Single comment topic classification with failover to multiple models, and concurrent worker pool for each model

def call_single_topic_llm_api(prompt, model_cfg):
    url = model_cfg["base_url"].rstrip("/") + model_cfg["path"]

    headers = {
        "Authorization": f"Bearer {model_cfg['api_token']}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": model_cfg["model_name"],
        "messages": [
            {"role": "system", "content": "你是一个严谨的中文影视评论主题分类助手。"},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0
    }

    last_error = None

    for attempt in range(model_cfg["max_retries"]):
        try:
            resp = requests.post(url, headers=headers, json=payload, timeout=model_cfg["timeout"])
            resp.raise_for_status()
            data = resp.json()
            return data["choices"][0]["message"]["content"]

        except Exception as e:
            last_error = e
            time.sleep(1.5 * (attempt + 1))

    raise RuntimeError(f"Model {model_cfg['name']} request failed: {last_error}")


# Prompt builder

def build_topic_llm_prompt(comment, candidate_labels=None):
    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    label_text = "、".join(candidate_labels)

    return f"""
你是一个中文影视评论主题分类助手。

请判断下面这条评论主要属于哪个主题类别。
只能从以下标签中选择一个，不允许自造新标签：

{label_text}

要求：
1. 只能返回一个最主要的主题
2. 只返回 JSON，不要输出其他文字

输出格式：
{{"topic_category":"剧情","reason":"一句话理由"}}

评论：
{comment}
""".strip()


# Output parser

def parse_topic_llm_output(raw_output, candidate_labels=None):
    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    raw_output = str(raw_output).strip()

    try:
        obj = json.loads(raw_output)
        topic_category = str(obj.get("topic_category", "")).strip()
        reason = str(obj.get("reason", "")).strip()

        if topic_category not in candidate_labels:
            topic_category = "其他"

        return {
            "topic_category": topic_category,
            "llm_topic_reason": reason,
            "llm_topic_raw_output": raw_output
        }

    except Exception:
        match = re.search(r'"topic_category"\s*:\s*"([^"]+)"', raw_output, flags=re.IGNORECASE)
        if match:
            topic_category = match.group(1).strip()
            if topic_category not in candidate_labels:
                topic_category = "Other"

            return {
                "topic_category": topic_category,
                "llm_topic_reason": "Non-standard JSON, regex extraction successful",
                "llm_topic_raw_output": raw_output
            }

        return {
            "topic_category": "Other",
            "llm_topic_reason": "JSON parsing failed, defaulting to Other",
            "llm_topic_raw_output": raw_output
        }


# Single comment topic classification with failover to multiple models, used by the worker threads.
# It tries each model in order until one succeeds, and returns a default "Other" category if all fail.

def review_single_topic_comment_with_failover(comment, model_candidates, candidate_labels=None):
    prompt = build_topic_llm_prompt(comment, candidate_labels=candidate_labels)

    last_error = None

    for model_cfg in model_candidates:
        try:
            raw_output = call_single_topic_llm_api(prompt, model_cfg)
            parsed = parse_topic_llm_output(raw_output, candidate_labels=candidate_labels)
            parsed["used_model"] = model_cfg["name"]
            return parsed

        except Exception as e:
            last_error = e
            continue

    return {
        "topic_category": "Other",
        "llm_topic_reason": f"All models failed: {last_error}",
        "llm_topic_raw_output": "",
        "used_model": "none"
    }


# Multi-threaded worker class for topic classification, with its own task queue and result storage.
# Each worker will process comments using its assigned model configuration,
#  and will use the failover function to try multiple models if needed.

class TopicModelWorker:
    def __init__(self, model_cfg, candidate_labels=None):
        self.model_cfg = model_cfg
        self.candidate_labels = candidate_labels
        self.task_queue = queue.Queue()
        self.result_dict = {}
        self.lock = threading.Lock()
        self.stop_signal = False

    def submit_task(self, idx, comment, all_model_cfgs):
        self.task_queue.put((idx, comment, all_model_cfgs))

    def worker_loop(self):
        while not self.stop_signal:
            try:
                item = self.task_queue.get(timeout=1)
            except queue.Empty:
                continue

            if item is None:
                self.task_queue.task_done()
                break

            idx, comment, all_model_cfgs = item

            failover_models = [self.model_cfg] + [
                m for m in all_model_cfgs if m["name"] != self.model_cfg["name"]
            ]

            result = review_single_topic_comment_with_failover(
                comment=comment,
                model_candidates=failover_models,
                candidate_labels=self.candidate_labels
            )

            with self.lock:
                self.result_dict[idx] = result

            self.task_queue.task_done()

    def run(self):
        self.executor = ThreadPoolExecutor(max_workers=self.model_cfg["thread_workers"])
        self.futures = [
            self.executor.submit(self.worker_loop)
            for _ in range(self.model_cfg["thread_workers"])
        ]

    def shutdown(self):
        self.stop_signal = True
        for _ in range(self.model_cfg["thread_workers"]):
            self.task_queue.put(None)
        self.task_queue.join()
        self.executor.shutdown(wait=True)


# Multi-model concurrent processing of comment topic classification, with failover and result aggregation.
# This function will create a pool of workers for each available model,
#  distribute the comments among them, and then aggregate the results back into a single DataFrame.

def analyze_comment_topic_dataframe_multi_model(
    df,
    season_col="season",
    comment_col="comment",
    candidate_labels=None,
    model_configs=None
):
    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    if model_configs is None:
        model_configs = AVAILABLE_TOPIC_MODELS

    if not model_configs:
        raise RuntimeError("No available topic models provided for analysis. Please check the model pool testing results.")

    required_cols = [season_col, comment_col]
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing fields: {missing_cols}")

    work_df = df[[season_col, comment_col]].copy()
    work_df = work_df[work_df[comment_col].notna()].copy()
    work_df[comment_col] = work_df[comment_col].astype(str).str.strip()
    work_df = work_df[work_df[comment_col] != ""].copy()
    work_df = work_df.reset_index(drop=True)

    work_df["topic_category"] = "Other"
    work_df["llm_topic_reason"] = ""
    work_df["used_model"] = ""

    model_workers = []
    for cfg in model_configs:
        worker = TopicModelWorker(model_cfg=cfg, candidate_labels=candidate_labels)
        worker.run()
        model_workers.append(worker)

    for idx, row in work_df.iterrows():
        comment = row[comment_col]
        target_worker = model_workers[idx % len(model_workers)]
        target_worker.submit_task(idx, comment, model_configs)

    for worker in model_workers:
        worker.task_queue.join()

    for worker in model_workers:
        for idx, result in worker.result_dict.items():
            work_df.at[idx, "topic_category"] = result["topic_category"]
            work_df.at[idx, "llm_topic_reason"] = result["llm_topic_reason"]
            work_df.at[idx, "used_model"] = result.get("used_model", "")

    for worker in model_workers:
        worker.shutdown()

    final_cols = [
        season_col,
        comment_col,
        "topic_category",
        "llm_topic_reason",
        "used_model"
    ]

    return work_df[final_cols]


def run_comment_topic_pipeline(
    mongo_uri_or_spark,
    source_db,
    source_collection,
    target_db,
    target_collection,
    season_col="season",
    comment_col="comment",
    candidate_labels=None,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True,
    model_configs=None
):
    spark = ensure_spark_session(mongo_uri_or_spark)
    mongo_uri = spark.conf.get("spark.mongodb.read.connection.uri")

    if candidate_labels is None:
        candidate_labels = DEFAULT_CANDIDATE_LABELS

    if model_configs is None:
        model_configs = AVAILABLE_TOPIC_MODELS

    if not model_configs:
        raise RuntimeError("No available topic models provided for analysis. Please check the model pool testing results.")

    source_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=source_collection,
        query={},
        projection={"_id": 0}
    )

    if len(source_spark_df.head(1)) == 0:
        print("The source collection has no data")
        return pd.DataFrame()

    source_df = source_spark_df.toPandas()

    result_df = analyze_comment_topic_dataframe_multi_model(
        df=source_df,
        season_col=season_col,
        comment_col=comment_col,
        candidate_labels=candidate_labels,
        model_configs=model_configs
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection,
        output_dir=output_dir
    )

    inserted_count = 0

    if not result_df.empty:
        result_spark_df = spark.createDataFrame(result_df)

        inserted_count = insert_dataframe_to_collection(
            df=result_spark_df,
            mongo_uri=mongo_uri,
            db_name=target_db,
            collection_name=target_collection,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=result_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No topic records generated")

    print(f"Source collection: {source_collection}")
    print(f"Number of source records: {len(source_df)}")
    print(f"Number of topic records: {len(result_df)}")
    print(f"Topic collection written successfully: {inserted_count} records")

    if not result_df.empty:
        print(f"Topic CSV exported successfully: {output_csv_path}")

    return result_df


topic_df = run_comment_topic_pipeline(
    mongo_uri_or_spark=CLIENT,
    source_db=DEFAULT_DB,
    source_collection="dws_comment_preprocessed",
    target_db=DEFAULT_DB,
    target_collection="dws_comment_topic_analysis",
    candidate_labels=DEFAULT_CANDIDATE_LABELS,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True,
    model_configs=AVAILABLE_TOPIC_MODELS
)

print(topic_df.head())

Source collection: dws_comment_preprocessed
Number of source records: 2285
Number of topic records: 2285
Topic collection written successfully: 2285 records
Topic CSV exported successfully: /content/dws_comment_topic_analysis.csv
   season                                            comment topic_category  \
0       9                                         就剩一季了。强迫症。             剧情
1       9     看的真快。乔伊被设定的越来越简单，钱德勒婚后不好玩了。依然喜欢ross，越发觉得莫妮卡不错。             演员
2       9  有点拖拉的一季，钱德勒和莫妮卡检查的时候我觉得好可怜，特别是结果出来的时候！一直认为麦克就是...             剧情
3       9                                        真的只剩下一季了...             情怀
4       9                               好喜欢RJ在一起~~让RR随风飘逝吧~~             情怀

                                 llm_topic_reason                 used_model
0                   评论提到剧集只剩一季，主要涉及剧情进展和观众对剧情的期待。         alibaba/qwen-turbo
1  Non-standard JSON, regex extraction successful          alibaba/kimi-k2.5
2                       评论主要围绕剧集节奏、情节发展和角色关系展开讨论。     deepseek/deepseek-chat
3                             评论表达对剧集即将结束的惋惜与不舍情感      alibaba/deepseek-v3.1
4                 评论表达了对角色关系的深情眷恋和情感共鸣，侧重情感记忆与情怀。  alibaba/qwen-turbo-latest

## Merage two results
Merge sentiment analysis results and topic classification results into one final comment analysis table

| Process Step | Description |
|---|---|
| Read sentiment analysis results | Read the comment sentiment analysis data from MongoDB |
| Read topic analysis results | Read the comment topic classification data from MongoDB |
| Check for empty input data | Stop the process if either input table is empty |
| Remove duplicate topic records | Remove duplicate topic results based on `season` and `comment`, keeping only the last record |
| Perform left-join merging | Use the sentiment analysis table as the primary table and merge the topic classification results based on the comment content |
| Fill missing topic values | Replace unmatched topic results with `Other` |
| Standardize output fields | Keep fields such as sentiment scores, final sentiment labels, topic categories, and LLM review results |
| Save the final results | Write the merged results into MongoDB and export them as a CSV file |

In [31]:
# Merge sentiment + topic
# Output collection: dws_comment_theme_analysis

def merge_sentiment_and_topic_dataframe(
    sentiment_df,
    topic_df,
    season_col="season",
    comment_col="comment"
):
    # To prevent duplicate keys in the topic table
    topic_df = topic_df.drop_duplicates(subset=[season_col, comment_col], keep="last").copy()

    merged_df = sentiment_df.merge(
        topic_df[[season_col, comment_col, "topic_category"]],
        on=[season_col, comment_col],
        how="left"
    )

    merged_df["topic_category"] = merged_df["topic_category"].fillna("其他")

    final_cols = [
        season_col,
        comment_col,
        "keyword",

        "star_negative", "star_neutral", "star_positive", "star_top_label", "star_top_score",
        "tri_negative", "tri_neutral", "tri_positive", "tri_top_label", "tri_top_score",

        "final_negative", "final_neutral", "final_positive",
        "sentiment_association",
        "decision_type",

        "topic_category",

        "llm_label",
        "llm_reason",
        "final_label_after_llm"
    ]

    return merged_df[final_cols]


def run_merge_theme_pipeline(
    mongo_uri_or_spark,
    source_db,
    sentiment_collection,
    topic_collection,
    target_db,
    target_collection,
    season_col="season",
    comment_col="comment",
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
):
    spark = ensure_spark_session(mongo_uri_or_spark)
    mongo_uri = spark.conf.get("spark.mongodb.read.connection.uri")

    sentiment_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=sentiment_collection,
        query={},
        projection={"_id": 0}
    )

    topic_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=topic_collection,
        query={},
        projection={"_id": 0}
    )

    if len(sentiment_spark_df.head(1)) == 0:
        print("Sentiment collection is empty")
        return pd.DataFrame()

    if len(topic_spark_df.head(1)) == 0:
        print("Topic collection is empty")
        return pd.DataFrame()

    sentiment_df = sentiment_spark_df.toPandas()
    topic_df = topic_spark_df.toPandas()

    merged_df = merge_sentiment_and_topic_dataframe(
        sentiment_df=sentiment_df,
        topic_df=topic_df,
        season_col=season_col,
        comment_col=comment_col
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection,
        output_dir=output_dir
    )

    inserted_count = 0

    if not merged_df.empty:
        merged_spark_df = spark.createDataFrame(merged_df)

        inserted_count = insert_dataframe_to_collection(
            df=merged_spark_df,
            mongo_uri=mongo_uri,
            db_name=target_db,
            collection_name=target_collection,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=merged_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No merged records generated")

    print(f"Sentiment records: {len(sentiment_df)}")
    print(f"Topic records: {len(topic_df)}")
    print(f"Merged records: {len(merged_df)}")
    print(f"Final merged collection written successfully: {inserted_count} records")

    if not merged_df.empty:
        print(f"Final merged CSV exported successfully: {output_csv_path}")

    return merged_df


final_df = run_merge_theme_pipeline(
    mongo_uri_or_spark=CLIENT,
    source_db=DEFAULT_DB,
    sentiment_collection="dws_comment_sentiment_analysis",
    topic_collection="dws_comment_topic_analysis",
    target_db=DEFAULT_DB,
    target_collection="dws_comment_theme_analysis",

    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
)

print(final_df.head())

Sentiment records: 2285
Topic records: 2285
Merged records: 2285
Final merged collection written successfully: 2285 records
Final merged CSV exported successfully: /content/dws_comment_theme_analysis.csv
   season                                            comment keyword  \
0       9                                         就剩一季了。强迫症。     强迫症
1       9     看的真快。乔伊被设定的越来越简单，钱德勒婚后不好玩了。依然喜欢ross，越发觉得莫妮卡不错。      简单
2       9  有点拖拉的一季，钱德勒和莫妮卡检查的时候我觉得好可怜，特别是结果出来的时候！一直认为麦克就是...      罗斯
3       9                                        真的只剩下一季了...      剩下
4       9                               好喜欢RJ在一起~~让RR随风飘逝吧~~    rjrr

   star_negative  star_neutral  star_positive star_top_label  star_top_score  \
0       0.462451      0.337643       0.199907       negative        0.462451
1       0.325473      0.480498       0.194029        neutral        0.444906
2       0.204436      0.388928       0.406636       positive        0.406636
3       0.428043      0.328210       0.243747       negative        0.428043
4       0.027889      0.190245       0.781866       positive        0.781866

   tri_negative  tri_neutral  ...  tri_top_score final_negative  \
0      0.429604     0.370642  ...       0.429604       0.449312
1      0.369912     0.251486  ...       0.424632       0.317823
2      0.584943     0.256847  ...       0.584943       1.000000
3      0.559296     0.334560  ...       0.559296       0.480545
4      0.083813     0.235418  ...       0.680768       0.050259

   final_neutral  final_positive  sentiment_association  \
0       0.350842        0.199846               negative
1       0.360086        0.322091                neutral
2       0.000000        0.000000               negative
3       0.330750        0.188705               negative
4       0.208315        0.741427               positive

                   decision_type topic_category llm_label  \
0                 weighted_merge             剧情   neutral
1                 weighted_merge             演员
2  llm_override_pos_neg_conflict             剧情  negative
3                 weighted_merge             情怀  negative
4                 weighted_merge             情怀

                        llm_reason final_label_after_llm
0          评论仅陈述事实和轻微个人感受，无明显褒贬倾向。               neutral
1                                                neutral
2  评论明确表达了对剧情拖拉、角色命运的不满，并直接批评了抄袭行为              negative
3    评论表达了明显的遗憾和失落情绪，暗示对剧集即将完结的不满。              negative
4                                               positive

[5 rows x 22 columns]

## Reduction Pipeline Output
Reduce the full comment analysis results

| Process Step | Description |
|---|---|
| Read source data | Read the full merged analysis results from MongoDB |
| Check for empty input | Stop the process if the source collection is empty |
| Validate required fields | Check whether the required fields exist: `season`, `comment`, `keyword`, `final_label_after_llm`, and `topic_category` |
| Select the final five fields | Keep only the five fields needed for ADS: season, comment, keyword, sentiment label, and topic category |
| Remove unnecessary ID field | Drop the `_id` column if it exists |
| Standardize field names | Rename the selected fields to the final ADS schema: `season`, `comment`, `keyword`, `sentiment_association`, and `topic_category` |
| Build the reduced result table | Generate a new DataFrame containing only the final five ADS fields |
| Write to target collection | Save the reduced results into a new MongoDB collection `ads_comment_theme_analysis` |
| Export CSV file | Export the final ADS result table as a CSV file with the same collection name |
| Print pipeline statistics | Output the source record count, ADS result count, inserted record count, and CSV export path |

In [32]:
# Merge result reduction to final 5 fields for ADS
# Output collection: ads_comment_theme_analysis


def build_ads_final_5_fields_dataframe(
    df,
    season_col="season",
    comment_col="comment",
    keyword_col="keyword",
    sentiment_col="final_label_after_llm",
    topic_col="topic_category"
):
    """
    Reduce the full analysis result table to the final 5 ADS fields:
    season, comment, keyword, sentiment_association, topic_category
    """
    required_cols = [season_col, comment_col, keyword_col, sentiment_col, topic_col]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing fields: {missing_cols}")

    ads_df = df[[season_col, comment_col, keyword_col, sentiment_col, topic_col]].copy()

    if "_id" in ads_df.columns:
        ads_df = ads_df.drop(columns=["_id"])

    ads_df = ads_df.rename(columns={
        season_col: "season",
        comment_col: "comment",
        keyword_col: "keyword",
        sentiment_col: "sentiment_association",
        topic_col: "topic_category"
    })

    return ads_df


def run_ads_final_5_fields_pipeline(
    mongo_uri_or_spark,
    source_db,
    source_collection,
    target_db,
    target_collection,
    season_col="season",
    comment_col="comment",
    keyword_col="keyword",
    sentiment_col="final_label_after_llm",
    topic_col="topic_category",
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
):
    """
    Read from MongoDB, reduce fields, write to a new collection,
    and export a CSV with the same name.
    """
    spark = ensure_spark_session(mongo_uri_or_spark)
    mongo_uri = spark.conf.get("spark.mongodb.read.connection.uri")

    source_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=source_db,
        collection_name=source_collection,
        query={},
        projection={"_id": 0}
    )

    if len(source_spark_df.head(1)) == 0:
        print("The source collection has no data")
        return pd.DataFrame()

    source_df = source_spark_df.toPandas()

    ads_df = build_ads_final_5_fields_dataframe(
        df=source_df,
        season_col=season_col,
        comment_col=comment_col,
        keyword_col=keyword_col,
        sentiment_col=sentiment_col,
        topic_col=topic_col
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection,
        output_dir=output_dir
    )

    inserted_count = 0

    if not ads_df.empty:
        ads_spark_df = spark.createDataFrame(ads_df)

        inserted_count = insert_dataframe_to_collection(
            df=ads_spark_df,
            mongo_uri=mongo_uri,
            db_name=target_db,
            collection_name=target_collection,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=ads_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No ADS result records generated")

    print(f"Source collection: {source_collection}")
    print(f"Number of source records: {len(source_df)}")
    print(f"Number of ADS result records: {len(ads_df)}")
    print(f"New collection written successfully: {inserted_count} records")

    if not ads_df.empty:
        print(f"CSV exported successfully: {output_csv_path}")

    return ads_df



ads_final_df = run_ads_final_5_fields_pipeline(
    mongo_uri_or_spark=CLIENT,
    source_db=DEFAULT_DB,
    source_collection="dws_comment_theme_analysis",
    target_db=DEFAULT_DB,
    target_collection="ads_comment_theme_analysis",
    season_col="season",
    comment_col="comment",
    keyword_col="keyword",
    sentiment_col="final_label_after_llm",
    topic_col="topic_category",
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
)

print(ads_final_df.head())

Source collection: dws_comment_theme_analysis
Number of source records: 2285
Number of ADS result records: 2285
New collection written successfully: 2285 records
CSV exported successfully: /content/ads_comment_theme_analysis.csv
   season                                            comment keyword  \
0       7                                     里程碑式情景喜剧！★★★★★      情景
1       7  一直以为让人从头笑到尾的喜剧才是可爱的，七季看完，看着怯懦的Chandler和强势的Moni...      强势
2       7   好吧。这季赶得特别不容易。要在2011年6月电影版出来前整完10季..........你可以的！      电影
3       7                                      经典看来早晚还是要看的。。      早晚
4       7                                              苏珊萨兰登      萨兰

  sentiment_association topic_category
0              positive             剧情
1               neutral             情怀
2              positive             情怀
3              positive             情怀
4               neutral             演员

## Season-Level Overall Evaluation
Generate the final season-level evaluation table

| Process Step | Description |
|---|---|
| Read input data | Read comment analysis results and season rating data from MongoDB |
| Check input validity | Stop the process if either input table is empty or required fields are missing |
| Clean and standardize data | Remove unnecessary `_id` fields and standardize sentiment labels |
| Aggregate sentiment statistics | Count the number of positive, negative, and neutral comments for each season |
| Compute total comment count | Calculate the total number of comments for each season |
| Merge season-level data | Merge the aggregated sentiment statistics with the season rating table by `season_id` |
| Fill missing values | Replace missing sentiment counts with `0` |
| Save final results | Write the final table to MongoDB and export it as a CSV file |

In [33]:
# Final season-level evaluation table creation by merging comment-level analysis results
#  with season-level ratings, and aggregating statistics.
# Output collection: ads_season_overall_evaluation


def create_ads_season_overall_evaluation_dataframe(
    comment_df,
    rating_df
):
    """
    Create the final ADS season-level evaluation DataFrame.

    Input:
    1. Comment analysis result table
       Fields: season, comment, keyword, sentiment_association, topic_category
    2. Original season rating table
       Fields: season, df_douban_rating, imdb_rating, rating_difference

    Output:
    - season_id
    - df_douban_rating
    - imdb_rating
    - rating_difference
    - positive_comment_cnt
    - negative_comment_cnt
    - netral_common_cnt
    - total_common_cnt
    """
    required_comment_cols = ["season", "sentiment_association"]
    required_rating_cols = ["season", "df_douban_rating", "imdb_rating", "rating_difference"]

    missing_comment_cols = [col for col in required_comment_cols if col not in comment_df.columns]
    missing_rating_cols = [col for col in required_rating_cols if col not in rating_df.columns]

    if missing_comment_cols:
        raise ValueError(f"Comment analysis result table is missing fields: {missing_comment_cols}")
    if missing_rating_cols:
        raise ValueError(f"Season rating table is missing fields: {missing_rating_cols}")

    work_comment_df = comment_df.copy()
    work_rating_df = rating_df.copy()

    if "_id" in work_comment_df.columns:
        work_comment_df = work_comment_df.drop(columns=["_id"])
    if "_id" in work_rating_df.columns:
        work_rating_df = work_rating_df.drop(columns=["_id"])

    work_comment_df["sentiment_association"] = (
        work_comment_df["sentiment_association"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    summary_df = (
        work_comment_df.groupby("season")["sentiment_association"]
        .value_counts()
        .unstack(fill_value=0)
        .reset_index()
    )

    for col in ["positive", "negative", "neutral"]:
        if col not in summary_df.columns:
            summary_df[col] = 0

    summary_df = summary_df.rename(columns={
        "season": "season_id",
        "positive": "positive_comment_cnt",
        "negative": "negative_comment_cnt",
        "neutral": "netral_common_cnt"
    })

    summary_df["total_common_cnt"] = (
        summary_df["positive_comment_cnt"]
        + summary_df["negative_comment_cnt"]
        + summary_df["netral_common_cnt"]
    )

    work_rating_df = work_rating_df.rename(columns={
        "season": "season_id"
    })

    final_df = work_rating_df.merge(summary_df, on="season_id", how="left")

    for col in [
        "positive_comment_cnt",
        "negative_comment_cnt",
        "netral_common_cnt",
        "total_common_cnt"
    ]:
        final_df[col] = final_df[col].fillna(0).astype(int)

    final_df = final_df[
        [
            "season_id",
            "df_douban_rating",
            "imdb_rating",
            "rating_difference",
            "positive_comment_cnt",
            "negative_comment_cnt",
            "netral_common_cnt",
            "total_common_cnt"
        ]
    ]

    return final_df


def run_ads_season_overall_evaluation_pipeline(
    mongo_uri_or_spark,
    db_name,
    comment_collection_name,
    rating_collection_name,
    target_collection_name,
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
):
    """
    Read two tables from MongoDB, aggregate statistics,
    write the result to a new collection, and export a CSV
    with the same name.
    """
    spark = ensure_spark_session(mongo_uri_or_spark)
    mongo_uri = spark.conf.get("spark.mongodb.read.connection.uri")

    comment_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=db_name,
        collection_name=comment_collection_name,
        query={},
        projection={"_id": 0}
    )

    rating_spark_df = load_mongo_to_dataframe(
        spark=spark,
        mongo_uri=mongo_uri,
        db_name=db_name,
        collection_name=rating_collection_name,
        query={},
        projection={"_id": 0}
    )

    if len(comment_spark_df.head(1)) == 0:
        print("The comment analysis collection has no data")
        return pd.DataFrame()

    if len(rating_spark_df.head(1)) == 0:
        print("The season rating collection has no data")
        return pd.DataFrame()

    comment_df = comment_spark_df.toPandas()
    rating_df = rating_spark_df.toPandas()

    final_df = create_ads_season_overall_evaluation_dataframe(
        comment_df=comment_df,
        rating_df=rating_df
    )

    output_csv_path = build_csv_path_from_collection_name(
        collection_name=target_collection_name,
        output_dir=output_dir
    )

    inserted_count = 0

    if not final_df.empty:
        final_spark_df = spark.createDataFrame(final_df)

        inserted_count = insert_dataframe_to_collection(
            df=final_spark_df,
            mongo_uri=mongo_uri,
            db_name=db_name,
            collection_name=target_collection_name,
            clear_first=clear_target_first
        )

        export_dataframe_to_csv(
            df=final_spark_df,
            output_csv_path=output_csv_path,
            encoding=csv_encoding
        )
    else:
        print("No result records generated")

    print(f"Comment analysis source collection: {comment_collection_name}")
    print(f"Rating source collection: {rating_collection_name}")
    print(f"Number of result records: {len(final_df)}")
    print(f"New collection written successfully: {inserted_count} records")

    if not final_df.empty:
        print(f"CSV exported successfully: {output_csv_path}")

    return final_df


final_df = run_ads_season_overall_evaluation_pipeline(
    mongo_uri_or_spark=CLIENT,
    db_name=DEFAULT_DB,
    comment_collection_name="ads_comment_theme_analysis",
    rating_collection_name="dws_season_rating_comparison",
    target_collection_name="ads_season_overall_evaluation",
    csv_encoding="utf-8",
    output_dir="/content",
    clear_target_first=True
)

print(final_df.head())

Comment analysis source collection: ads_comment_theme_analysis
Rating source collection: dws_season_rating_comparison
Number of result records: 10
New collection written successfully: 10 records
CSV exported successfully: /content/ads_season_overall_evaluation.csv
   season_id  df_douban_rating  imdb_rating  rating_difference  \
0          5               9.8          8.6                1.2
1          8               9.7          8.4                1.3
2          9               9.7          8.3                1.4
3          2               9.8          8.5                1.3
4          4               9.7          8.5                1.2

   positive_comment_cnt  negative_comment_cnt  netral_common_cnt  \
0                   157                    25                 53
1                   125                    41                 51
2                   128                    50                 47
3                   166                    15                 54
4                   124                    41                 60

   total_common_cnt
0               235
1               217
2               225
3               235
4               225

## Export CSV

In [34]:
# Output all collections to CSV for backup and manual review


export_all_collections_to_csv(
    mongo_uri_or_spark=CLIENT,
    db_name=DEFAULT_DB,
    output_dir="/content/drive/MyDrive/STAT2630 GROUP",
    encoding="utf-8",
    drop_id=True
)

dws_comment_model_filtered export success: /content/drive/MyDrive/STAT2630 GROUP/dws_comment_model_filtered.csv, total 2499 rows.
dws_comment_theme_analysis export success: /content/drive/MyDrive/STAT2630 GROUP/dws_comment_theme_analysis.csv, total 2285 rows.
dws_douban_comment export success: /content/drive/MyDrive/STAT2630 GROUP/dws_douban_comment.csv, total 3999 rows.
dws_comment_sentiment_analysis export success: /content/drive/MyDrive/STAT2630 GROUP/dws_comment_sentiment_analysis.csv, total 2285 rows.
dws_season_rating_comparison export success: /content/drive/MyDrive/STAT2630 GROUP/dws_season_rating_comparison.csv, total 10 rows.
dws_comment_rule_filtered export success: /content/drive/MyDrive/STAT2630 GROUP/dws_comment_rule_filtered.csv, total 3552 rows.
ads_comment_theme_analysis export success: /content/drive/MyDrive/STAT2630 GROUP/ads_comment_theme_analysis.csv, total 2285 rows.
ads_season_overall_evaluation export success: /content/drive/MyDrive/STAT2630 GROUP/ads_season_overall_evaluation.csv, total 10 rows.
dws_comment_preprocessed export success: /content/drive/MyDrive/STAT2630 GROUP/dws_comment_preprocessed.csv, total 2285 rows.
dws_comment_topic_analysis export success: /content/drive/MyDrive/STAT2630 GROUP/dws_comment_topic_analysis.csv, total 2285 rows.
All export finished, total 10 CSV files.

['/content/drive/MyDrive/STAT2630 GROUP/dws_comment_model_filtered.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_comment_theme_analysis.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_douban_comment.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_comment_sentiment_analysis.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_season_rating_comparison.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_comment_rule_filtered.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/ads_comment_theme_analysis.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/ads_season_overall_evaluation.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_comment_preprocessed.csv',
 '/content/drive/MyDrive/STAT2630 GROUP/dws_comment_topic_analysis.csv']